Repository prgrms-be-devcourse/springboot-jpa, pull requests merged in 2022-05, with the labels that each got.

#11 [2기-P] 김수빈 Mission 1: JPA 소개
  jpa2/.gitignore
  jpa2/build.gradle
  jpa2/gradle/wrapper/gradle-wrapper.jar
  jpa2/gradle/wrapper/gradle-wrapper.properties
  jpa2/gradlew
  jpa2/gradlew.bat
  jpa2/settings.gradle
  jpa2/src/main/java/com/part4/jpa2/Jpa2Application.java
  jpa2/src/main/java/com/part4/jpa2/config/DataSourceConfig.java
  jpa2/src/main/java/com/part4/jpa2/domain/Customer.java
  jpa2/src/main/java/com/part4/jpa2/domain/CustomerRepository.java
  jpa2/src/main/resources/application.yaml
  jpa2/src/test/java/com/part4/jpa2/CustomerRepositoryTest.java
Labels: Team-Armand, 💧 순한맛

#18 [2기-P] 곽동운 Mission 1: JPA 소개
  .gitignore
  .idea/.gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/git_toolbox_prj.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  kdt.iml
  pom.xml
  src/main/java/org/prgrms/kdt/Application.java
  src/main/java/org/prgrms/kdt/config/DataSourceConfig.java
  src/main/java/org/prgrms/kdt/domain/Customer.java
  src/main/java/org/prgrms/kdt/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/org/prgrms/kdt/ApplicationTest.java
  src/test/java/org/prgrms/kdt/domain/CustomerRepositoryTest.java
Labels: Team-Kyu

#12 [2기-P] 박혜빈 Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/study/springbootJpa/Config/DataSourceConfig.java
  src/main/java/com/study/springbootJpa/SpringbootJpaApplication.java
  src/main/java/com/study/springbootJpa/domain/Customer.java
  src/main/java/com/study/springbootJpa/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/study/springbootJpa/SpringbootJpaApplicationTests.java
  src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
Labels: Team-Kyu

#33 [2기-P] 김성현 Mission1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/prgrms/assignment/jpa/JpaApplication.java
  src/main/java/prgrms/assignment/jpa/config/DataSourceConfig.java
  src/main/java/prgrms/assignment/jpa/domain/Customer.java
  src/main/java/prgrms/assignment/jpa/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/prgrms/assignment/jpa/JpaApplicationTests.java
  src/test/java/prgrms/assignment/jpa/repository/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Hoon

#19 [2기-P] 김병연 Mission 1: JPA 소개
  app/.gitignore
  app/build.gradle
  app/gradle/wrapper/gradle-wrapper.jar
  app/gradle/wrapper/gradle-wrapper.properties
  app/gradlew
  app/gradlew.bat
  app/settings.gradle
  app/src/main/java/com/programmers/app/AppApplication.java
  app/src/main/java/com/programmers/app/config/DataSourceConfig.java
  app/src/main/java/com/programmers/app/domain/Customer.java
  app/src/main/java/com/programmers/app/domain/CustomerRepository.java
  app/src/main/resources/application.yml
  app/src/test/java/com/programmers/app/AppApplicationTests.java
  app/src/test/java/com/programmers/app/domain/CustomerRepositoryTest.java
Labels: Team-Kyu

#13 [2기-P] 유민환 Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  docs/README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/prgrms/springJpa/SpringbootJpaApplication.java
  src/main/java/com/prgrms/springJpa/config/DataSourceConfig.java
  src/main/java/com/prgrms/springJpa/domain/Customer.java
  src/main/java/com/prgrms/springJpa/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/prgrms/springJpa/SpringbootJpaApplicationTests.java
  src/test/java/com/prgrms/springJpa/domain/CustomerRepositoryTest.java
Labels: Team-Armand, 🔥 매운맛

#15 [2기-P] 강용수 Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/prgms/mission_jpa/MissionJpaApplication.java
  src/main/java/com/prgms/mission_jpa/config/DataSourceConfig.java
  src/main/java/com/prgms/mission_jpa/customer/Customer.java
  src/main/java/com/prgms/mission_jpa/customer/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/prgms/mission_jpa/MissionJpaApplicationTests.java
  src/test/java/com/prgms/mission_jpa/customer/CustomerRepositoryTest.java
Labels: Team-Armand, 🔥 매운맛

#10 [2기-P] 김형욱 Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/kdt/lecture/LectureApplication.java
  src/main/java/com/kdt/lecture/config/DataSourceConfig.java
  src/main/java/com/kdt/lecture/domain/Customer.java
  src/main/java/com/kdt/lecture/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/kdt/lecture/LectureApplicationTests.java
  src/test/java/com/kdt/lecture/domain/CustomerRepositoryTest.java
Labels: Team-Kyu

#6 [2기-P] 박우진 Mission1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/prgrms/springjpa/SpringJpaApplication.java
  src/main/java/org/prgrms/springjpa/config/DataSourceConfig.java
  src/main/java/org/prgrms/springjpa/domain/Customer.java
  src/main/java/org/prgrms/springjpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/org/prgrms/springjpa/domain/CustomerRepositoryTest.java
Labels: Team-Armand

#28 [2기-P] 이인후 Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/lecture/LectureApplication.java
  src/main/java/com/kdt/lecture/config/DataSourceConfig.java
  src/main/java/com/kdt/lecture/domain/Customer.java
  src/main/java/com/kdt/lecture/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/kdt/lecture/repository/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Hoon

#32 [2기-P] 정윤오 Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/assignment1/Assignment1Application.java
  src/main/java/com/example/assignment1/config/DataSourceConfig.java
  src/main/java/com/example/assignment1/domain/Customer.java
  src/main/java/com/example/assignment1/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/assignment1/Assignment1ApplicationTests.java
  src/test/java/com/example/assignment1/domain/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Hoon

#14 [2기-P] 김재욱 Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/will/jpapractice/JpaPracticeApplication.java
  src/main/java/com/will/jpapractice/config/DataSourceConfig.java
  src/main/java/com/will/jpapractice/domain/Customer.java
  src/main/java/com/will/jpapractice/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/will/jpapractice/JpaPracticeApplicationTests.java
  src/test/java/com/will/jpapractice/domain/CustomerRepositoryTest.java
Labels: Team-Armand, 💧 순한맛

#39 [2-P] 김성현 Mission 2: 영속성 컨텍스트
  src/test/java/prgrms/assignment/jpa/repository/PersistenceContextLifecycleTest.java
Labels: 🔥 매운맛, Team-Hoon

#34 [2기-P] 이용훈 Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/jpaproject/JpaProjectApplication.java
  src/main/java/com/kdt/jpaproject/config/DataSourceConfig.java
  src/main/java/com/kdt/jpaproject/domain/Customer.java
  src/main/java/com/kdt/jpaproject/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/jpaproject/JpaProjectApplicationTests.java
  src/test/java/com/kdt/jpaproject/domain/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Hoon

#37 [2기-P] 곽동운 Mission 2: 영속성컨텍스트
  pom.xml
  src/main/java/org/prgrms/kdt/domain/Customer.java
  src/test/java/org/prgrms/kdt/domain/CustomerPersistenceContextTest.java
Labels: Team-Kyu

#58 [2기-P] 정윤오 Mission 2: 영속성 컨텍스트
  src/test/java/com/example/assignment1/domain/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-Hoon

#73 [2기-P] 이용훈 Mission 2: 영속성 컨텍스트
  src/main/java/com/kdt/jpaproject/domain/Customer.java
  src/test/java/com/kdt/jpaproject/PersistenceContextTest.java
  src/test/java/com/kdt/jpaproject/domain/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Hoon

#57 [2기-P] 이인후 Mission 2: 영속성 컨텍스트
  src/test/java/com/kdt/lecture/repository/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-Hoon

#43 [2기-C 길근오] CustomerRepository 생성 & CRUD 테스트
  springboot-jpa/.gitignore
  springboot-jpa/README.md
  springboot-jpa/pom.xml
  springboot-jpa/src/main/java/com/example/springjpa/SpringJpaApplication.java
  springboot-jpa/src/main/java/com/example/springjpa/config/DataSourceConfig.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/Customer.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/Item.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/Member.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/Order.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/OrderItem.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/OrderStatus.java
  springboot-jpa/src/main/java/com/example/springjpa/inherit/Car.java
  springboot-jpa/src/main/java/com/example/springjpa/inherit/Food.java
  springboot-jpa/src/main/java/com/example/springjpa/inherit/Furniture.java
  springboot-jpa/src/main/java/com/example/springjpa/inherit/ParentItem.java
  springboot-jpa/src/main/java/com/example/springjpa/repository/CustomerRepository.java
  springboot-jpa/src/main/resources/application.yaml
  springboot-jpa/src/test/java/com/example/springjpa/inherit/InheritTest.java
  springboot-jpa/src/test/java/com/example/springjpa/repository/CustomerRepositoryTest.java
  springboot-jpa/src/test/java/com/example/springjpa/repository/EntityManagerTest.java
  springboot-jpa/src/test/java/com/example/springjpa/repository/RelationTest.java
Labels: Team-Wook

#59 [2기-P] 김형욱 Mission 2: 영속성컨텍스트
  src/main/java/com/kdt/lecture/domain/Customer.java
  src/main/resources/application.yml
  src/test/java/com/kdt/lecture/domain/PersistTest.java
Labels: Team-Kyu

#22 [2기-C] 남득윤 Mission1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/chapter1/Chapter1Application.java
  src/main/java/com/example/chapter1/config/DataSourceConfig.java
  src/main/java/com/example/chapter1/domain/Customer.java
  src/main/java/com/example/chapter1/domain/CustomerRepository.java
  src/main/resources/application.properties
  src/test/java/com/example/chapter1/domain/CustomerRepositoryTest.java
Labels: Team-Wook

#47 [2기-P] 유민환 Mission 2: 영속성컨텍스트
  src/main/resources/application.yaml
  src/test/java/com/prgrms/springJpa/domain/PersistenceContextTest.java
Labels: Team-Armand, 🔥 매운맛

#16 [2기-C] 박현지 Mission1: JPA 소개
  .gitignore
  README.md
  pom.xml
  src/main/java/com/example/jpalecture/JpaLectureApplication.java
  src/main/java/com/example/jpalecture/config/DataSourceConfig.java
  src/main/java/com/example/jpalecture/domain/Customer.java
  src/main/java/com/example/jpalecture/domain/CustomerRepository.java
  src/main/java/com/example/jpalecture/domain/order/BaseEntity.java
  src/main/java/com/example/jpalecture/domain/order/Car.java
  src/main/java/com/example/jpalecture/domain/order/Food.java
  src/main/java/com/example/jpalecture/domain/order/Furniture.java
  src/main/java/com/example/jpalecture/domain/order/Item.java
  src/main/java/com/example/jpalecture/domain/order/Member.java
  src/main/java/com/example/jpalecture/domain/order/Order.java
  src/main/java/com/example/jpalecture/domain/order/OrderItem.java
  src/main/java/com/example/jpalecture/domain/order/OrderStatus.java
  src/main/java/com/example/jpalecture/domain/order/parent/Parent.java
  src/main/java/com/example/jpalecture/domain/order/parent/ParentId.java
  src/main/resources/application.yml
  src/test/java/com/example/jpalecture/JpaLectureApplicationTests.java
  src/test/java/com/example/jpalecture/domain/CustomerRepositoryTest.java
  src/test/java/com/example/jpalecture/domain/PersistenceContextTest.java
  src/test/java/com/example/jpalecture/order/ImproveMappingTest.java
  src/test/java/com/example/jpalecture/order/OrderPersistenceTest.java
  src/test/java/com/example/jpalecture/order/ProxyTest.java
  src/test/java/resources/application-test.yml
Labels: Team-Wook

#17 [2기-C] 변주한 Mission1: JPA 소개
  .gitignore
  README.md
  pom.xml
  src/main/java/com/jpa/springboot/SpringbootJpaApplication.java
  src/main/java/com/jpa/springboot/config/DataSourceConfig.java
  src/main/java/com/jpa/springboot/domain/Customer.java
  src/main/java/com/jpa/springboot/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/jpa/springboot/SpringbootJpaApplicationTests.java
  src/test/java/com/jpa/springboot/domain/CustomerRepositoryTest.java
Labels: Team-Wook

#82 [2기-C] 정하영 Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/kdtjpa/KdtJpaApplication.java
  src/main/java/com/example/kdtjpa/config/DataSourceConfig.java
  src/main/java/com/example/kdtjpa/domain/Customer.java
  src/main/java/com/example/kdtjpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/kdtjpa/domain/CustomerRepositoryTest.java
Labels: Team-Ray

#85 [2기-C] 유재희 : JPA 위클리 미션 1 : sparkles: feat : Customer JPA CRUD 테스트 실습
  lec_JPA/.gitignore
  lec_JPA/build.gradle
  lec_JPA/gradle/wrapper/gradle-wrapper.jar
  lec_JPA/gradle/wrapper/gradle-wrapper.properties
  lec_JPA/gradlew
  lec_JPA/gradlew.bat
  lec_JPA/settings.gradle
  lec_JPA/src/main/java/com/prgrms/lec_jpa/config/DataSourceConfig.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Customer.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/CustomerRepository.java
  lec_JPA/src/main/resources/application.yml
  lec_JPA/src/test/java/com/prgrms/lec_jpa/domain/CustomerRepositoryTest.java
Labels: Team-Ray, 🔥 매운맛

#41 [2기-P] 강용수 Mission 2: 영속성컨텍스트
  src/test/java/com/prgms/mission_jpa/customer/CustomerPersistenceContextTest.java
Labels: Team-Armand, 🔥 매운맛

#81 [2기-P] 박우진 Mission 2: 영속성 컨텍스트
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/prgrms/springjpa/SpringJpaApplication.java
  src/main/java/org/prgrms/springjpa/config/DataSourceConfig.java
  src/main/java/org/prgrms/springjpa/domain/Customer.java
  src/main/java/org/prgrms/springjpa/domain/CustomerRepository.java
  src/main/java/org/prgrms/springjpa/domain/order/Item.java
  src/main/java/org/prgrms/springjpa/domain/order/Member.java
  src/main/java/org/prgrms/springjpa/domain/order/Order.java
  src/main/java/org/prgrms/springjpa/domain/order/OrderItem.java
  src/main/java/org/prgrms/springjpa/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/org/prgrms/springjpa/domain/CustomerRepositoryTest.java
  src/test/java/org/prgrms/springjpa/domain/PersistenceContextTest.java
Labels: Team-Armand

#89 [2기-P] 이예림 Mission 2: 영속성 컨텍스트
  demo/src/main/java/com/example/demo/domain/Customer.java
  demo/src/main/java/com/example/demo/repository/CustomerRepository.java
  demo/src/main/resources/application.yaml
  demo/src/test/java/com/example/demo/persistence/CustomerPersistenceTest.java
  demo/src/test/java/com/example/demo/repository/CustomerRepositoryTest.java
Labels: Team-Hoon

#56 [2기-P]김용철 Mission1 : JPA 소개 리뷰 부탁드립니다
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/kdt/lecture/LectureApplication.java
  src/main/java/com/kdt/lecture/domain/Customer.java
  src/main/java/com/kdt/lecture/repository/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/lecture/repository/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-R

#65 [2기-C] 김재욱 Mission 2: 영속성 컨텍스트
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/will/jpapractice/JpaPracticeApplication.java
  src/main/java/com/will/jpapractice/config/DataSourceConfig.java
  src/main/java/com/will/jpapractice/domain/Customer.java
  src/main/java/com/will/jpapractice/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/will/jpapractice/JpaPracticeApplicationTests.java
  src/test/java/com/will/jpapractice/domain/CustomerRepositoryTest.java
  src/test/java/com/will/jpapractice/domain/PersistenceContextTest.java
Labels: Team-Armand, 🔥 매운맛

#106 [2기-C] 정하영 - Mission 3: 연관관계 매핑
  src/main/java/com/example/kdtjpa/domain/BaseEntity.java
  src/main/java/com/example/kdtjpa/domain/customer/Customer.java
  src/main/java/com/example/kdtjpa/domain/customer/CustomerRepository.java
  src/main/java/com/example/kdtjpa/domain/item/Car.java
  src/main/java/com/example/kdtjpa/domain/item/Food.java
  src/main/java/com/example/kdtjpa/domain/item/Furniture.java
  src/main/java/com/example/kdtjpa/domain/item/Item.java
  src/main/java/com/example/kdtjpa/domain/member/Member.java
  src/main/java/com/example/kdtjpa/domain/order/Order.java
  src/main/java/com/example/kdtjpa/domain/order/OrderStatus.java
  src/main/java/com/example/kdtjpa/domain/orderItem/OrderItem.java
  src/test/java/com/example/kdtjpa/domain/customer/CustomerRepositoryTest.java
Labels: Team-Ray

#109 [2기-P] 김산 Mission1 : JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/kdt/springbootjpa/common/config/DataSourceConfig.java
  src/main/java/com/kdt/springbootjpa/customer/domain/Customer.java
  src/main/java/com/kdt/springbootjpa/customer/repository/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/springbootjpa/customer/repository/CustomerRepositoryTest.java
  src/test/resources/application.yaml
Labels: Team-Ray

#83 [2기-P] 김진욱 springboot-jpa mission 1입니다.
  .gitignore
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/jpademo/JpaDemoApplication.java
  src/main/java/com/example/jpademo/config/DataSourceConfig.java
  src/main/java/com/example/jpademo/domain/Customer.java
  src/main/java/com/example/jpademo/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/jpademo/JpaDemoApplicationTests.java
  src/test/java/com/example/jpademo/domain/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-R

#53 [2기-P] 최인창 springboot-jpa weekly misson 코드 리뷰 부탁 드려요~
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/programmers/kdt/studyjpa/StudyJpaApplication.java
  src/main/java/org/programmers/kdt/studyjpa/config/DataSourceConfig.java
  src/main/java/org/programmers/kdt/studyjpa/domain/Customer.java
  src/main/java/org/programmers/kdt/studyjpa/domain/CustomerRepository.java
  src/main/java/org/programmers/kdt/studyjpa/domain/order/Item.java
  src/main/java/org/programmers/kdt/studyjpa/domain/order/Member.java
  src/main/java/org/programmers/kdt/studyjpa/domain/order/Order.java
  src/main/java/org/programmers/kdt/studyjpa/domain/order/OrderItem.java
  src/main/java/org/programmers/kdt/studyjpa/domain/order/OrderStatus.java
  src/main/resources/application.yaml
  src/test/java/org/programmers/kdt/studyjpa/StudyJpaApplicationTests.java
  src/test/java/org/programmers/kdt/studyjpa/domain/CustomerRepositoryTest.java
  src/test/java/org/programmers/kdt/studyjpa/domain/PersistenceContextTest.java
  src/test/java/org/programmers/kdt/studyjpa/domain/order/OrderPersistenceTest.java
Labels: 🔥 매운맛, Team-R

#113 [2기-C] 김산 - :sparkles: Mission 3: 연관관계 매핑
  src/main/java/com/kdt/springbootjpa/common/entity/BaseEntity.java
  src/main/java/com/kdt/springbootjpa/item/domain/Car.java
  src/main/java/com/kdt/springbootjpa/item/domain/Food.java
  src/main/java/com/kdt/springbootjpa/item/domain/Furniture.java
  src/main/java/com/kdt/springbootjpa/item/domain/Item.java
  src/main/java/com/kdt/springbootjpa/member/domain/Member.java
  src/main/java/com/kdt/springbootjpa/order/domain/Order.java
  src/main/java/com/kdt/springbootjpa/order/domain/OrderItem.java
  src/main/java/com/kdt/springbootjpa/order/domain/OrderStatus.java
Labels: Team-Ray

#114 [2기-C] 유재희 jap misson 3 연관관계 매핑 실습
  lec_JPA/build.gradle
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/BaseEntity.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Item.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Member.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Order.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/OrderItem.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/OrderStatus.java
  lec_JPA/src/test/java/com/prgrms/lec_jpa/domain/OrderPersistentTest.java
Labels: Team-Ray, 🔥 매운맛

#70 [2기-C] 황승한 Mission 3: 연관관계매핑
  .gitignore
  HELP.md
  jpa.iml
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/prgms/jpa/DataSourceConfig.java
  src/main/java/org/prgms/jpa/JpaApplication.java
  src/main/java/org/prgms/jpa/domain/Customer.java
  src/main/java/org/prgms/jpa/domain/CustomerRepository.java
  src/main/java/org/prgms/jpa/domain/order/Item.java
  src/main/java/org/prgms/jpa/domain/order/Member.java
  src/main/java/org/prgms/jpa/domain/order/Order.java
  src/main/java/org/prgms/jpa/domain/order/OrderItem.java
  src/main/java/org/prgms/jpa/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/org/prgms/jpa/JpaApplicationTests.java
  src/test/java/org/prgms/jpa/domain/CustomerRepositoryTest.java
  src/test/java/org/prgms/jpa/domain/OrderMappingTest.java
Labels: Team-Wook

#105 [2기-P] 이연우 Mission1 : JPA 소개
  .gitignore
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/springjpa/SpringJpaApplication.java
  src/main/java/com/example/springjpa/customer/Customer.java
  src/main/java/com/example/springjpa/customer/CustomerJpaRepository.java
  src/main/resources/application.yaml
  src/test/java/com/example/springjpa/SpringJpaApplicationTests.java
  src/test/java/com/example/springjpa/customer/CustomerJpaRepositoryTest.java
Labels: 💧 순한맛, Team-R

#68 [2기-P]김용철 Mission 2: 영속성 컨텍스트
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/kdt/lecture/LectureApplication.java
  src/main/java/com/kdt/lecture/domain/Customer.java
  src/main/java/com/kdt/lecture/repository/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/lecture/repository/CustomerRepositoryTest.java
  src/test/java/com/kdt/lecture/repository/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-R

#129 [2기 -C] 유재희 :fire: delete : 롬복 의존성 제거
  lec_JPA/build.gradle
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/BaseEntity.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Item.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Member.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Order.java
  lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/OrderItem.java
  lec_JPA/src/test/java/com/prgrms/lec_jpa/domain/CustomerRepositoryTest.java
  lec_JPA/src/test/java/com/prgrms/lec_jpa/domain/OrderPersistentTest.java
Labels: Team-Ray, 🔥 매운맛

#2 [2기-C]스프링부트 JPA 위클리미션 - JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/devcoursejpa/jpa/JpaApplication.java
  src/main/java/devcoursejpa/jpa/config/DataSourceConfig.java
  src/main/java/devcoursejpa/jpa/domain/Customer.java
  src/main/java/devcoursejpa/jpa/domain/CustomerRepository.java
  src/main/java/devcoursejpa/jpa/domain/Name.java
  src/main/resources/application.yml
  src/test/java/devcoursejpa/jpa/JpaApplicationTests.java
  src/test/java/devcoursejpa/jpa/domain/CustomerRepositoryTest.java
Labels: Team-Marco

#3 [2-C]방은혁 'Mission 1 : JPA 소개' 코드 리뷰 부탁드립니다!
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/prgms/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/prgms/springbootjpa/config/DataSourceConfig.java
  src/main/java/com/prgms/springbootjpa/domain/Customer.java
  src/main/java/com/prgms/springbootjpa/domain/Name.java
  src/main/java/com/prgms/springbootjpa/exception/ExceptionMessage.java
  src/main/java/com/prgms/springbootjpa/exception/InvalidNameLengthException.java
  src/main/java/com/prgms/springbootjpa/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/prgms/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/prgms/springbootjpa/domain/NameTest.java
  src/test/java/com/prgms/springbootjpa/lifecycle/PersistenceContextTest.java
  src/test/java/com/prgms/springbootjpa/repository/CustomerRepositoryTest.java
Labels: Team-Marco, 🔥 매운맛

#38 [2-C] 방은혁 Mission 2: 영속성컨텍스트
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/prgms/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/prgms/springbootjpa/config/DataSourceConfig.java
  src/main/java/com/prgms/springbootjpa/domain/Customer.java
  src/main/java/com/prgms/springbootjpa/domain/Name.java
  src/main/java/com/prgms/springbootjpa/exception/ExceptionMessage.java
  src/main/java/com/prgms/springbootjpa/exception/InvalidNameLengthException.java
  src/main/java/com/prgms/springbootjpa/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/prgms/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/prgms/springbootjpa/domain/NameTest.java
  src/test/java/com/prgms/springbootjpa/lifecycle/PersistenceContextTest.java
  src/test/java/com/prgms/springbootjpa/repository/CustomerRepositoryTest.java
Labels: Team-Marco

#131 [2기-C]류영준 -Customer JPA CRUD 테스트
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/JpaWeekly/Application.java
  src/main/java/com/kdt/JpaWeekly/domain/customer/Customer.java
  src/main/java/com/kdt/JpaWeekly/domain/customer/CustomerRepository.java
  src/test/java/com/kdt/JpaWeekly/CustomerRepositoryTest.java
Labels: Team-Ray

#127 [2기-C]유도진-Mission1:단일 엔티티를 이용한 CRUD를 구현
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/dojinyou/devcourse/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/config/DataSourceConfig.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/customer/CustomerEntity.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/customer/CustomerRepository.java
  src/test/java/com/dojinyou/devcourse/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/dojinyou/devcourse/springbootjpa/customer/CustomerRepositoryTest.java
Labels: Team-Ray, 🔥 매운맛

#134 [2기-C]류영준 - 연관관계 매핑
  build.gradle
  src/main/java/com/kdt/JpaWeekly/common/domain/BaseEntity.java
  src/main/java/com/kdt/JpaWeekly/domain/item/Car.java
  src/main/java/com/kdt/JpaWeekly/domain/item/Food.java
  src/main/java/com/kdt/JpaWeekly/domain/item/Furniture.java
  src/main/java/com/kdt/JpaWeekly/domain/item/Item.java
  src/main/java/com/kdt/JpaWeekly/domain/member/Member.java
  src/main/java/com/kdt/JpaWeekly/domain/order/Order.java
  src/main/java/com/kdt/JpaWeekly/domain/order/OrderItem.java
  src/main/java/com/kdt/JpaWeekly/domain/order/OrderStatus.java
Labels: Team-Ray

#130 [2기-C] 김산 - JPA Mission 3 롬복 제거
  build.gradle
  src/main/java/com/kdt/springbootjpa/common/entity/BaseEntity.java
  src/main/java/com/kdt/springbootjpa/item/domain/Car.java
  src/main/java/com/kdt/springbootjpa/item/domain/Food.java
  src/main/java/com/kdt/springbootjpa/item/domain/Furniture.java
  src/main/java/com/kdt/springbootjpa/item/domain/Item.java
  src/main/java/com/kdt/springbootjpa/member/domain/Member.java
  src/main/java/com/kdt/springbootjpa/order/domain/Order.java
  src/main/java/com/kdt/springbootjpa/order/domain/OrderItem.java
Labels: Team-Ray

#128 [2기-C] 정하영 - JPA Mission 3 롬복 의존성 제거
  pom.xml
  src/main/java/com/example/kdtjpa/domain/BaseEntity.java
  src/main/java/com/example/kdtjpa/domain/customer/Customer.java
  src/main/java/com/example/kdtjpa/domain/item/Car.java
  src/main/java/com/example/kdtjpa/domain/item/Food.java
  src/main/java/com/example/kdtjpa/domain/item/Furniture.java
  src/main/java/com/example/kdtjpa/domain/item/Item.java
  src/main/java/com/example/kdtjpa/domain/member/Member.java
  src/main/java/com/example/kdtjpa/domain/order/Order.java
  src/main/java/com/example/kdtjpa/domain/orderItem/OrderItem.java
  src/test/java/com/example/kdtjpa/domain/customer/CustomerRepositoryTest.java
Labels: Team-Ray

#140 [2기 - P] 김산 :sparkles: Audit 적용
  src/main/java/com/kdt/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/kdt/springbootjpa/common/entity/AccountAuditAware.java
  src/main/java/com/kdt/springbootjpa/common/entity/BaseEntity.java
  src/main/java/com/kdt/springbootjpa/customer/domain/Customer.java
  src/main/java/com/kdt/springbootjpa/item/domain/Car.java
  src/test/java/com/kdt/springbootjpa/customer/repository/CustomerRepositoryTest.java
Labels: Team-Ray

#141 [2기-C]유도진-Mission1:단일 엔티티를 이용한 CRUD를 구현
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/dojinyou/devcourse/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/customer/CustomerEntity.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/customer/CustomerRepository.java
  src/test/java/com/dojinyou/devcourse/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/dojinyou/devcourse/springbootjpa/customer/CustomerRepositoryTest.java
  src/test/java/com/dojinyou/devcourse/springbootjpa/customer/PersistenceContextTest.java
Labels: Team-Ray, 🔥 매운맛

#142 [2기-C]유도진-Mission3: 연관관계 매핑 실습
  src/main/java/com/dojinyou/devcourse/springbootjpa/common/entity/BaseEntity.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/item/Car.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/item/Food.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/item/Furniture.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/item/Item.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/member/Member.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/order/Order.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/order/OrderItem.java
  src/main/java/com/dojinyou/devcourse/springbootjpa/order/OrderStatus.java
Labels: Team-Ray, 🔥 매운맛

#75 [2기-P] 마지영 Mission1
  springboot-jpa/.gitignore
  springboot-jpa/.mvn/wrapper/maven-wrapper.jar
  springboot-jpa/.mvn/wrapper/maven-wrapper.properties
  springboot-jpa/mvnw
  springboot-jpa/mvnw.cmd
  springboot-jpa/pom.xml
  springboot-jpa/src/main/java/com/example/springbootjpa/SpringbootJpaApplication.java
  springboot-jpa/src/main/java/com/example/springbootjpa/config/DataSourceConfig.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/Customer.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/CustomerRepository.java
  springboot-jpa/src/main/resources/application.yml
  springboot-jpa/src/test/java/com/example/springbootjpa/SpringbootJpaApplicationTests.java
  springboot-jpa/src/test/java/com/example/springbootjpa/mission1/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-R

#98 [2기-P] 마지영 Mission 2: 영속성 컨텍스트 & Mission 3: 연관관계 매핑
  springboot-jpa/.gitignore
  springboot-jpa/.mvn/wrapper/maven-wrapper.jar
  springboot-jpa/.mvn/wrapper/maven-wrapper.properties
  springboot-jpa/mvnw
  springboot-jpa/mvnw.cmd
  springboot-jpa/pom.xml
  springboot-jpa/src/main/java/com/example/springbootjpa/SpringbootJpaApplication.java
  springboot-jpa/src/main/java/com/example/springbootjpa/config/DataSourceConfig.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/Customer.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/CustomerRepository.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/domain/Item.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/domain/Member.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/domain/Order.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/domain/OrderItem.java
  springboot-jpa/src/main/java/com/example/springbootjpa/mission1/domain/OrderStatus.java
  springboot-jpa/src/main/resources/application.yml
  springboot-jpa/src/test/java/com/example/springbootjpa/SpringbootJpaApplicationTests.java
  springboot-jpa/src/test/java/com/example/springbootjpa/mission1/CustomerRepositoryTest.java
  springboot-jpa/src/test/java/com/example/springbootjpa/mission2/PersistenceContextTest.java
  springboot-jpa/src/test/java/com/example/springbootjpa/mission3/Mission3Test.java
Labels: 🔥 매운맛, Team-R

#146 [2-C]최현웅 Mission1 ~ 3 : 코드리뷰요청합니다.
  .gitignore
  README.md
  pom.xml
  src/main/java/com/programmers/jpa/JpaApplication.java
  src/main/java/com/programmers/jpa/member/Member.java
  src/main/java/com/programmers/jpa/member/MemberRepository.java
  src/main/java/com/programmers/jpa/order/Item.java
  src/main/java/com/programmers/jpa/order/Order.java
  src/main/java/com/programmers/jpa/order/OrderItem.java
  src/main/java/com/programmers/jpa/order/OrderRepository.java
  src/main/java/com/programmers/jpa/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/com/programmers/jpa/JpaApplicationTests.java
  src/test/java/com/programmers/jpa/member/DomainMappingTest.java
  src/test/java/com/programmers/jpa/member/SingleEntityTest.java
Labels: Team-Blackdog

#21 [2기-P] 이창호 Mission 1: JPA 소개
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/jpasettingpractice/JpaSettingPracticeApplication.java
  src/main/java/com/example/jpasettingpractice/config/DataSourceConfig.java
  src/main/java/com/example/jpasettingpractice/domain/Customer.java
  src/main/java/com/example/jpasettingpractice/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/example/jpasettingpractice/domain/CustomerRepositoryTest.java
Labels: Team-Tyler, 🔥 매운맛

#133 [2기-C]최지훈 - JPA 미션1~3 코드 리뷰 요청합니다!
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/example/springbootjpa/domain/base/BaseEntity.java
  src/main/java/com/example/springbootjpa/domain/items/Book.java
  src/main/java/com/example/springbootjpa/domain/items/Fruit.java
  src/main/java/com/example/springbootjpa/domain/items/Item.java
  src/main/java/com/example/springbootjpa/domain/main/Member.java
  src/main/java/com/example/springbootjpa/domain/main/Order.java
  src/main/java/com/example/springbootjpa/domain/main/OrderItem.java
  src/main/java/com/example/springbootjpa/domain/main/OrderStatus.java
  src/main/java/com/example/springbootjpa/repository/MemberJpaRepository.java
  src/main/java/com/example/springbootjpa/repository/MemberRepository.java
  src/main/java/com/example/springbootjpa/service/DefaultMemberService.java
  src/main/java/com/example/springbootjpa/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/example/springbootjpa/DomainMappingTest.java
  src/test/java/com/example/springbootjpa/SpringbootJpaApplicationTests.java
Labels: Team-Blackdog, 🔥 매운맛

#110 [2기-P] 박진형 Mission 3: 연관관계매핑
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/lecturejpa/LectureJpaApplication.java
  src/main/java/com/example/lecturejpa/config/DataSourceConfig.java
  src/main/java/com/example/lecturejpa/domain/customer/Customer.java
  src/main/java/com/example/lecturejpa/domain/customer/CustomerRepository.java
  src/main/java/com/example/lecturejpa/domain/order/Item.java
  src/main/java/com/example/lecturejpa/domain/order/Member.java
  src/main/java/com/example/lecturejpa/domain/order/Order.java
  src/main/java/com/example/lecturejpa/domain/order/OrderItem.java
  src/main/java/com/example/lecturejpa/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/com/example/lecturejpa/LectureJpaApplicationTests.java
  src/test/java/com/example/lecturejpa/domain/customer/CustomerRepositoryTest.java
  src/test/java/com/example/lecturejpa/domain/customer/PersistenceContextTest.java
  src/test/java/com/example/lecturejpa/domain/order/OrderPersistenceTest.java
Labels: Team-Kyu

#5 [2기-P] 박진형 Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/lecturejpa/LectureJpaApplication.java
  src/main/java/com/example/lecturejpa/config/DataSourceConfig.java
  src/main/java/com/example/lecturejpa/domain/Customer.java
  src/main/java/com/example/lecturejpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/lecturejpa/LectureJpaApplicationTests.java
  src/test/java/com/example/lecturejpa/domain/CustomerRepositoryTest.java
Labels: Team-Kyu

#123 [2기-C] 정해민 Mission 3: 연관관계 매핑
  .gitignore
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/programmers/jpa/SpringbootJpaMissionApplication.java
  src/main/java/com/programmers/jpa/domain/order/Item.java
  src/main/java/com/programmers/jpa/domain/order/Member.java
  src/main/java/com/programmers/jpa/domain/order/Order.java
  src/main/java/com/programmers/jpa/domain/order/OrderItem.java
  src/main/java/com/programmers/jpa/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/com/programmers/jpa/domain/order/OrderTest.java
Labels: Team-Blackdog, 🔥 매운맛

#67 [2기-C] 정해민 Mission1. JPA소개
  .gitignore
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/programmers/jpa/CustomerRepository.java
  src/main/java/com/programmers/jpa/SpringbootJpaMissionApplication.java
  src/main/java/com/programmers/jpa/domain/Customer.java
  src/main/resources/application.yml
  src/test/java/com/programmers/jpa/CustomerRepositoryTest.java
Labels: Team-Blackdog, 🔥 매운맛

#126 [2기-P]김용철 JPA Mission 3 : 연관관계 매핑 코드리뷰 부탁드립니다.
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/kdt/lecture/LectureApplication.java
  src/main/java/com/kdt/lecture/domain/Customer.java
  src/main/java/com/kdt/lecture/domain/order/Item.java
  src/main/java/com/kdt/lecture/domain/order/Member.java
  src/main/java/com/kdt/lecture/domain/order/Order.java
  src/main/java/com/kdt/lecture/domain/order/OrderItem.java
  src/main/java/com/kdt/lecture/domain/order/OrderStatus.java
  src/main/java/com/kdt/lecture/repository/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/lecture/domain/order/EntityRegister.java
  src/test/java/com/kdt/lecture/domain/order/MemberToOrderTest.java
  src/test/java/com/kdt/lecture/domain/order/OrderDomainTest.java
  src/test/java/com/kdt/lecture/domain/order/OrderItemToItemTest.java
  src/test/java/com/kdt/lecture/domain/order/OrderToOrderItemTest.java
  src/test/java/com/kdt/lecture/repository/CustomerRepositoryTest.java
  src/test/java/com/kdt/lecture/repository/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-R

#62 [2기-P 이수연] SpringBoot JPA 미션 1~3 제출합니다
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/example/springbootjpa/config/DataSourceConfig.java
  src/main/java/com/example/springbootjpa/domain/BaseEntity.java
  src/main/java/com/example/springbootjpa/domain/Car.java
  src/main/java/com/example/springbootjpa/domain/Customer.java
  src/main/java/com/example/springbootjpa/domain/Food.java
  src/main/java/com/example/springbootjpa/domain/Furniture.java
  src/main/java/com/example/springbootjpa/domain/Item.java
  src/main/java/com/example/springbootjpa/domain/Order.java
  src/main/java/com/example/springbootjpa/domain/OrderItem.java
  src/main/java/com/example/springbootjpa/domain/OrderStatus.java
  src/main/java/com/example/springbootjpa/repository/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/example/springbootjpa/PersistenceContextLifeCycleTest.java
  src/test/java/com/example/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/example/springbootjpa/domain/CustomerTest.java
  src/test/java/com/example/springbootjpa/domain/MappingTest.java
Labels: Team-Tyler, 🔥 매운맛

#30 [2기-P] 이일환 Mission 1: JPA 소개 리뷰 부탁드립니다!
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/pppp0722/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/pppp0722/springbootjpa/config/DataSourceConfig.java
  src/main/java/com/pppp0722/springbootjpa/domain/Customer.java
  src/main/java/com/pppp0722/springbootjpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/pppp0722/springbootjpa/domain/CustomerRepositoryTest.java
Labels: Team-Tyler, 🔥 매운맛

#54 [2기-P] 최연호 Mission 1: JPA 소개 리뷰 부탁드립니다
  kdt-jpa/.gitignore
  kdt-jpa/mvnw
  kdt-jpa/mvnw.cmd
  kdt-jpa/pom.xml
  kdt-jpa/src/main/java/com/kdt/jpa/KdtJpaApplication.java
  kdt-jpa/src/main/java/com/kdt/jpa/config/DataSourceConfig.java
  kdt-jpa/src/main/java/com/kdt/jpa/customer/domain/Customer.java
  kdt-jpa/src/main/java/com/kdt/jpa/customer/repository/CustomerRepository.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/BaseEntity.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Car.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Food.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Furniture.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Item.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Member.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Order.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/OrderItem.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/OrderStatus.java
  kdt-jpa/src/main/resources/application.yml
  kdt-jpa/src/test/java/com/kdt/jpa/KdtJpaApplicationTests.java
  kdt-jpa/src/test/java/com/kdt/jpa/customer/repository/CustomerRepositoryTest.java
  kdt-jpa/src/test/java/com/kdt/jpa/customer/repository/PersistenceContextTest.java
  kdt-jpa/src/test/java/com/kdt/jpa/order/MappingTest.java
Labels: Team-Tyler, 🔥 매운맛

#116 [2기-P] 최연호 Mission 3: 연관관계 매핑
  kdt-jpa/.gitignore
  kdt-jpa/mvnw
  kdt-jpa/mvnw.cmd
  kdt-jpa/pom.xml
  kdt-jpa/src/main/java/com/kdt/jpa/KdtJpaApplication.java
  kdt-jpa/src/main/java/com/kdt/jpa/config/DataSourceConfig.java
  kdt-jpa/src/main/java/com/kdt/jpa/customer/domain/Customer.java
  kdt-jpa/src/main/java/com/kdt/jpa/customer/repository/CustomerRepository.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/BaseEntity.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Car.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Food.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Furniture.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Item.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Member.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/Order.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/OrderItem.java
  kdt-jpa/src/main/java/com/kdt/jpa/order/domain/OrderStatus.java
  kdt-jpa/src/main/resources/application.yml
  kdt-jpa/src/test/java/com/kdt/jpa/KdtJpaApplicationTests.java
  kdt-jpa/src/test/java/com/kdt/jpa/customer/repository/CustomerRepositoryTest.java
  kdt-jpa/src/test/java/com/kdt/jpa/customer/repository/PersistenceContextTest.java
  kdt-jpa/src/test/java/com/kdt/jpa/order/MappingTest.java
Labels: Team-Tyler, 🔥 매운맛

#72 [2기-P] 박혜빈 Mission 3: 연관관계 매핑
  src/main/java/com/study/springbootJpa/domain/Item.java
  src/main/java/com/study/springbootJpa/domain/Member.java
  src/main/java/com/study/springbootJpa/domain/Order.java
  src/main/java/com/study/springbootJpa/domain/OrderItem.java
  src/main/java/com/study/springbootJpa/domain/OrderStatus.java
  src/main/java/com/study/springbootJpa/repository/Customer.java
  src/main/java/com/study/springbootJpa/repository/CustomerRepository.java
  src/test/java/com/study/springbootJpa/OrderMappingTest.java
  src/test/java/com/study/springbootJpa/PersistenceContextTest.java
  src/test/java/com/study/springbootJpa/SpringbootJpaApplicationTests.java
  src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
Labels: Team-Kyu

#100 [2기-P] 김형욱 Mission 3: 연관관계 매핑
  src/main/java/com/kdt/lecture/common/BaseEntity.java
  src/main/java/com/kdt/lecture/config/DataSourceConfig.java
  src/main/java/com/kdt/lecture/customer/Customer.java
  src/main/java/com/kdt/lecture/customer/CustomerRepository.java
  src/main/java/com/kdt/lecture/order/Car.java
  src/main/java/com/kdt/lecture/order/Food.java
  src/main/java/com/kdt/lecture/order/Furniture.java
  src/main/java/com/kdt/lecture/order/Item.java
  src/main/java/com/kdt/lecture/order/Member.java
  src/main/java/com/kdt/lecture/order/Order.java
  src/main/java/com/kdt/lecture/order/OrderItem.java
  src/main/java/com/kdt/lecture/order/OrderStatus.java
  src/test/java/com/kdt/lecture/customer/CustomerRepositoryTest.java
  src/test/java/com/kdt/lecture/customer/PersistTest.java
  src/test/java/com/kdt/lecture/order/MappingTest.java
Labels: Team-Kyu

#88 [2기-P] 곽동운 Mission 3: 연관관계 매핑
  src/main/java/org/prgrms/kdt/domain/order/Item.java
  src/main/java/org/prgrms/kdt/domain/order/Member.java
  src/main/java/org/prgrms/kdt/domain/order/Order.java
  src/main/java/org/prgrms/kdt/domain/order/OrderItem.java
  src/main/java/org/prgrms/kdt/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/org/prgrms/kdt/domain/order/AssociationMappingTest.java
Labels: Team-Kyu

#77 [2기-P] 김병연 Mission 3: 연관관계매핑
  app/src/main/java/com/programmers/app/domain/BaseEntity.java
  app/src/main/java/com/programmers/app/domain/order/Order.java
  app/src/main/java/com/programmers/app/domain/order/OrderItem.java
  app/src/main/java/com/programmers/app/domain/order/OrderStatus.java
  app/src/main/java/com/programmers/app/domain/order/item/Car.java
  app/src/main/java/com/programmers/app/domain/order/item/Food.java
  app/src/main/java/com/programmers/app/domain/order/item/Furniture.java
  app/src/main/java/com/programmers/app/domain/order/item/Item.java
  app/src/main/java/com/programmers/app/domain/order/member/Member.java
Labels: Team-Kyu, 🔥 매운맛
