Repository prgrms-be-devcourse/springboot-jpa, pull requests merged in 2022-12, with the labels that each got.

#163 [3기-C 김기웅] Mission 1: JPA 소개
  LectureJpa/.gitignore
  LectureJpa/.mvn/wrapper/maven-wrapper.properties
  LectureJpa/HELP.md
  LectureJpa/mvnw
  LectureJpa/mvnw.cmd
  LectureJpa/pom.xml
  LectureJpa/src/main/java/com/kdt/lecture/LectureJpa/LectureJpaApplication.java
  LectureJpa/src/main/java/com/kdt/lecture/LectureJpa/config/DataSourceConfig.java
  LectureJpa/src/main/java/com/kdt/lecture/LectureJpa/domain/Customer.java
  LectureJpa/src/main/java/com/kdt/lecture/LectureJpa/domain/CustomerRepository.java
  LectureJpa/src/main/resources/application.properties
  LectureJpa/src/test/java/com/kdt/lecture/LectureJpa/LectureJpaApplicationTests.java
  LectureJpa/src/test/java/com/kdt/lecture/LectureJpa/domain/CustomerRepositoryTest.java
Labels: Team-F, 🔥 매운맛

#176 [3기-C 공태현] Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/example/springbootjpa/domain/Customer.java
  src/main/java/com/example/springbootjpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/example/springbootjpa/domain/CustomerRepositoryTest.java
Labels: Team-Marco, 💧 순한맛

#8 [2기-C] 이한주 Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/programmers/jpa/ProgrammersJpaHomeworkApplication.java
  src/main/java/com/programmers/jpa/config/DataSourceConfig.java
  src/main/java/com/programmers/jpa/domain/Customer.java
  src/main/java/com/programmers/jpa/domain/CustomerRepository.java
  src/main/java/com/programmers/jpa/domain/Name.java
  src/main/resources/application.yml
  src/test/java/com/programmers/jpa/ProgrammersJpaHomeworkApplicationTests.java
  src/test/java/com/programmers/jpa/domain/CustomerRepositoryTest.java
  src/test/java/com/programmers/jpa/domain/CustomerTest.java
  src/test/java/com/programmers/jpa/domain/PersistenceContext.java
Labels: Team-Marco

#9 [2기-C] 강태산 Mission 1: JPA 소개
  springboot-jpa/.gitignore
  springboot-jpa/.mvn/wrapper/maven-wrapper.jar
  springboot-jpa/.mvn/wrapper/maven-wrapper.properties
  springboot-jpa/mvnw
  springboot-jpa/mvnw.cmd
  springboot-jpa/pom.xml
  springboot-jpa/src/main/java/com/example/springjpa/SpringJpaApplication.java
  springboot-jpa/src/main/java/com/example/springjpa/config/DataSourceConfig.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/Customer.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/Item.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/Member.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/Order.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/OrderItem.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/OrderStatus.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/Orders.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/vo/Name.java
  springboot-jpa/src/main/java/com/example/springjpa/exception/NoStockException.java
  springboot-jpa/src/main/java/com/example/springjpa/repository/CustomerRepository.java
  springboot-jpa/src/main/resources/application.yml
  springboot-jpa/src/test/java/com/example/springjpa/SpringJpaApplicationTests.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/CustomerRepositoryTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/PersistenceContextTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/common/EntityManagerTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/EntityUtil.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/MemberPersistenceTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/OrderItemPersistenceTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/OrderPersistenceTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/vo/NameTest.java
Labels: Team-Marco, 🔥 매운맛

#36 [2기-C] 정다현 Mission 2: 영속성컨텍스트
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/prgrms/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/prgrms/springbootjpa/config/DataSourceConfig.java
  src/main/java/com/prgrms/springbootjpa/domain/Customer.java
  src/main/java/com/prgrms/springbootjpa/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/prgrms/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/prgrms/springbootjpa/domain/CustomerPersistenceContextTest.java
  src/test/java/com/prgrms/springbootjpa/repository/CustomerRepositoryTest.java
Labels: Team-Marco

#74 [2기-C] 정다현 Mission 3: 연관관계매핑
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/prgrms/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/prgrms/springbootjpa/config/DataSourceConfig.java
  src/main/java/com/prgrms/springbootjpa/domain/Customer.java
  src/main/java/com/prgrms/springbootjpa/domain/Item.java
  src/main/java/com/prgrms/springbootjpa/domain/Order.java
  src/main/java/com/prgrms/springbootjpa/domain/OrderItem.java
  src/main/java/com/prgrms/springbootjpa/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/prgrms/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/prgrms/springbootjpa/domain/CustomerPersistenceContextTest.java
  src/test/java/com/prgrms/springbootjpa/domain/EntityMappingTest.java
  src/test/java/com/prgrms/springbootjpa/repository/CustomerRepositoryTest.java
Labels: Team-Marco

#103 [2기-C] 이한주 Mission 3: 연관관계 매핑 실습
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/programmers/jpa/ProgrammersJpaHomeworkApplication.java
  src/main/java/com/programmers/jpa/config/DataSourceConfig.java
  src/main/java/com/programmers/jpa/domain/Customer.java
  src/main/java/com/programmers/jpa/domain/CustomerRepository.java
  src/main/java/com/programmers/jpa/domain/order/Item.java
  src/main/java/com/programmers/jpa/domain/order/Member.java
  src/main/java/com/programmers/jpa/domain/order/Order.java
  src/main/java/com/programmers/jpa/domain/order/OrderItem.java
  src/main/java/com/programmers/jpa/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/com/programmers/jpa/ProgrammersJpaHomeworkApplicationTests.java
  src/test/java/com/programmers/jpa/domain/CustomerRepositoryTest.java
  src/test/java/com/programmers/jpa/domain/PersistenceContext.java
  src/test/java/com/programmers/jpa/domain/order/OrderPersistenceTest.java
Labels: Team-Marco

#148 [2-C] 방은혁 Mission 3: 연관관계 매핑
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/prgms/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/prgms/springbootjpa/config/DataSourceConfig.java
  src/main/java/com/prgms/springbootjpa/domain/customer/Customer.java
  src/main/java/com/prgms/springbootjpa/domain/customer/Name.java
  src/main/java/com/prgms/springbootjpa/domain/order/BaseEntity.java
  src/main/java/com/prgms/springbootjpa/domain/order/Member.java
  src/main/java/com/prgms/springbootjpa/domain/order/Order.java
  src/main/java/com/prgms/springbootjpa/domain/order/OrderItem.java
  src/main/java/com/prgms/springbootjpa/domain/order/OrderStatus.java
  src/main/java/com/prgms/springbootjpa/domain/order/item/Car.java
  src/main/java/com/prgms/springbootjpa/domain/order/item/Food.java
  src/main/java/com/prgms/springbootjpa/domain/order/item/Furniture.java
  src/main/java/com/prgms/springbootjpa/domain/order/item/Item.java
  src/main/java/com/prgms/springbootjpa/domain/order/vo/Name.java
  src/main/java/com/prgms/springbootjpa/domain/order/vo/NickName.java
  src/main/java/com/prgms/springbootjpa/domain/order/vo/OrderItems.java
  src/main/java/com/prgms/springbootjpa/domain/order/vo/Orders.java
  src/main/java/com/prgms/springbootjpa/domain/order/vo/Price.java
  src/main/java/com/prgms/springbootjpa/domain/order/vo/Quantity.java
  src/main/java/com/prgms/springbootjpa/exception/ExceptionMessage.java
  src/main/java/com/prgms/springbootjpa/exception/InvalidNameLengthException.java
  src/main/java/com/prgms/springbootjpa/exception/InvalidPriceRangeException.java
  src/main/java/com/prgms/springbootjpa/exception/InvalidQuantityRangeException.java
  src/main/java/com/prgms/springbootjpa/exception/NoAvailableQuantityException.java
  src/main/java/com/prgms/springbootjpa/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/prgms/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/prgms/springbootjpa/domain/customer/NameTest.java
  src/test/java/com/prgms/springbootjpa/domain/order/MappingTest.java
  src/test/java/com/prgms/springbootjpa/domain/order/item/ItemTest.java
  src/test/java/com/prgms/springbootjpa/domain/order/vo/NameTest.java
  src/test/java/com/prgms/springbootjpa/domain/order/vo/NickNameTest.java
  src/test/java/com/prgms/springbootjpa/domain/order/vo/OrderItemsTest.java
  src/test/java/com/prgms/springbootjpa/domain/order/vo/OrdersTest.java
  src/test/java/com/prgms/springbootjpa/domain/order/vo/PriceTest.java
  src/test/java/com/prgms/springbootjpa/domain/order/vo/QuantityTest.java
  src/test/java/com/prgms/springbootjpa/lifecycle/PersistenceContextTest.java
  src/test/java/com/prgms/springbootjpa/repository/CustomerRepositoryTest.java
Labels: Team-Marco, 🔥 매운맛

#118 [2기-C] 김지웅 JPA 연관관계 매핑
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/devcoursejpa/jpa/JpaApplication.java
  src/main/java/devcoursejpa/jpa/config/DataSourceConfig.java
  src/main/java/devcoursejpa/jpa/domain/Customer.java
  src/main/java/devcoursejpa/jpa/domain/CustomerRepository.java
  src/main/java/devcoursejpa/jpa/domain/Item.java
  src/main/java/devcoursejpa/jpa/domain/Member.java
  src/main/java/devcoursejpa/jpa/domain/Name.java
  src/main/java/devcoursejpa/jpa/domain/Order.java
  src/main/java/devcoursejpa/jpa/domain/OrderItem.java
  src/main/java/devcoursejpa/jpa/domain/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/devcoursejpa/jpa/JpaApplicationTests.java
  src/test/java/devcoursejpa/jpa/domain/CustomerRepositoryTest.java
  src/test/java/devcoursejpa/jpa/domain/MappingRelationshipTest.java
  src/test/java/devcoursejpa/jpa/domain/PersistenceContextTest.java
Labels: Team-Marco

#76 [2기-C] 이한주 Mission 2: 영속성컨텍스트
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/programmers/jpa/ProgrammersJpaHomeworkApplication.java
  src/main/java/com/programmers/jpa/config/DataSourceConfig.java
  src/main/java/com/programmers/jpa/domain/Customer.java
  src/main/java/com/programmers/jpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/programmers/jpa/ProgrammersJpaHomeworkApplicationTests.java
  src/test/java/com/programmers/jpa/domain/CustomerRepositoryTest.java
  src/test/java/com/programmers/jpa/domain/PersistenceContext.java
Labels: Team-Marco

#104 [2-C] 강태산 Mission 3: 연관관계 매핑
  springboot-jpa/.gitignore
  springboot-jpa/.mvn/wrapper/maven-wrapper.jar
  springboot-jpa/.mvn/wrapper/maven-wrapper.properties
  springboot-jpa/mvnw
  springboot-jpa/mvnw.cmd
  springboot-jpa/pom.xml
  springboot-jpa/src/main/java/com/example/springjpa/SpringJpaApplication.java
  springboot-jpa/src/main/java/com/example/springjpa/config/DataSourceConfig.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/Customer.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/Item.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/Member.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/Order.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/OrderItem.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/OrderStatus.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/Orders.java
  springboot-jpa/src/main/java/com/example/springjpa/domain/order/vo/Name.java
  springboot-jpa/src/main/java/com/example/springjpa/exception/NoStockException.java
  springboot-jpa/src/main/java/com/example/springjpa/repository/CustomerRepository.java
  springboot-jpa/src/main/resources/application.yml
  springboot-jpa/src/test/java/com/example/springjpa/SpringJpaApplicationTests.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/CustomerRepositoryTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/PersistenceContextTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/common/EntityManagerTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/EntityUtil.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/MemberPersistenceTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/OrderItemPersistenceTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/OrderPersistenceTest.java
  springboot-jpa/src/test/java/com/example/springjpa/domain/order/vo/NameTest.java
Labels: Team-Marco

#199 [3기-C 최은비] Mission 2 : 영속성 컨텍스트
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/jpaproject/JpaProjectApplication.java
  src/main/java/com/kdt/jpaproject/config/DataSourceConfig.java
  src/main/java/com/kdt/jpaproject/domain/Customer.java
  src/main/java/com/kdt/jpaproject/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/jpaproject/JpaProjectApplicationTests.java
  src/test/java/com/kdt/jpaproject/domain/CustomerRepositoryTest.java
  src/test/java/com/kdt/jpaproject/domain/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-R

#172 [3기-C 박현서] Mission 1: JPA 소개
  .gitignore
  HELP.md
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/devcourse/mission/MissionApplication.java
  src/main/java/com/devcourse/mission/domain/customer/entity/Customer.java
  src/main/java/com/devcourse/mission/domain/customer/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/devcourse/mission/MissionApplicationTests.java
  src/test/java/com/devcourse/mission/domain/customer/repository/CustomerRepositoryTest.java
  src/test/resources/application.yml
Labels: 🔥 매운맛, Team-R

#173 [3기-C 박현서] Mission 2: 영속성 컨텍스트
  .gitignore
  HELP.md
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/devcourse/mission/MissionApplication.java
  src/main/java/com/devcourse/mission/domain/customer/entity/Customer.java
  src/main/java/com/devcourse/mission/domain/customer/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/devcourse/mission/MissionApplicationTests.java
  src/test/java/com/devcourse/mission/domain/customer/repository/CustomerRepositoryTest.java
  src/test/java/com/devcourse/mission/domain/customer/repository/DataJpaPersistenceTest.java
  src/test/java/com/devcourse/mission/domain/customer/repository/JpaPersistenceTest.java
  src/test/java/resources/application-test.yml
Labels: 🔥 매운맛, Team-R

#160 [3기-C 김영빈] Mission 1: JPA 소개
  .gitignore
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/kdt/jpaproject/SpringbootJpaApplication.java
  src/main/java/com/kdt/jpaproject/config/DataSourceConfig.java
  src/main/java/com/kdt/jpaproject/domain/Customer.java
  src/main/java/com/kdt/jpaproject/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/jpaproject/JPATest.java
  src/test/java/com/kdt/jpaproject/SpringbootJpaApplicationTests.java
Labels: Team-F, 🔥 매운맛

#192 [3기-C 김태희] Mission 2 : 영속성 컨텍스트
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/kdt/jpa/SpringbootJpaApplication.java
  src/main/java/com/kdt/jpa/config/DataSourceConfig.java
  src/main/java/com/kdt/jpa/domain/Customer.java
  src/main/java/com/kdt/jpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/kdt/jpa/SpringbootJpaApplicationTests.java
  src/test/java/com/kdt/jpa/domain/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-Hoon

#182 [3기-C 박현서] Mission 3: 연관관계 매핑
  .gitignore
  HELP.md
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/devcourse/mission/MissionApplication.java
  src/main/java/com/devcourse/mission/domain/customer/entity/Customer.java
  src/main/java/com/devcourse/mission/domain/customer/repository/CustomerRepository.java
  src/main/java/com/devcourse/mission/domain/customer/service/CustomerService.java
  src/main/java/com/devcourse/mission/domain/item/entity/Item.java
  src/main/java/com/devcourse/mission/domain/item/repository/ItemRepository.java
  src/main/java/com/devcourse/mission/domain/item/service/ItemService.java
  src/main/java/com/devcourse/mission/domain/order/entity/Order.java
  src/main/java/com/devcourse/mission/domain/order/repository/OrderRepository.java
  src/main/java/com/devcourse/mission/domain/order/service/OrderService.java
  src/main/java/com/devcourse/mission/domain/orderitem/entity/OrderItem.java
  src/main/java/com/devcourse/mission/domain/orderitem/repository/OrderItemRepository.java
  src/main/resources/application.yml
  src/test/java/com/devcourse/mission/MissionApplicationTests.java
  src/test/java/com/devcourse/mission/domain/customer/repository/CustomerRepositoryTest.java
  src/test/java/com/devcourse/mission/domain/customer/repository/DataJpaPersistenceTest.java
  src/test/java/com/devcourse/mission/domain/customer/repository/JpaPersistenceTest.java
  src/test/java/com/devcourse/mission/domain/item/repository/ItemRepositoryTest.java
  src/test/java/com/devcourse/mission/domain/item/service/ItemServiceTest.java
  src/test/java/com/devcourse/mission/domain/order/repository/OrderRepositoryTest.java
  src/test/java/com/devcourse/mission/domain/order/service/OrderServiceTest.java
  src/test/resources/application-test.yml
Labels: 🔥 매운맛, Team-R

#164 [3기-C 이동준] 미션 1 리뷰 부탁드립니다!
  .gitignore
  pom.xml
  src/main/java/com/example/springboot_jpa/SpringbootJpaApplication.java
  src/main/java/com/example/springboot_jpa/domain/Customer.java
  src/main/java/com/example/springboot_jpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/springboot_jpa/SpringbootJpaApplicationTests.java
  src/test/java/com/example/springboot_jpa/domain/CustomerRepositoryTest.java
Labels: Team-F, 🔥 매운맛

#167 [3기-C 장주영] SpringBoot-Part4 Mission1 제출드립니다.
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/springbootjpamission1/SpringbootJpaMission1Application.java
  src/main/java/com/example/springbootjpamission1/domain/customer/entity/Customer.java
  src/main/java/com/example/springbootjpamission1/domain/customer/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/springbootjpamission1/SpringbootJpaMission1ApplicationTests.java
  src/test/java/com/example/springbootjpamission1/domain/customer/repository/CustomerRepositoryTest.java
Labels: Team-F, 🔥 매운맛

#193 [3기-C 장영지] JPA 위클리 미션 1, 2, 3 제출
  mission1/.gitignore
  mission1/.mvn/wrapper/maven-wrapper.jar
  mission1/.mvn/wrapper/maven-wrapper.properties
  mission1/mvnw
  mission1/mvnw.cmd
  mission1/pom.xml
  mission1/src/main/java/com/example/mission1/Mission1Application.java
  mission1/src/main/java/com/example/mission1/domain/Customer.java
  mission1/src/main/java/com/example/mission1/domain/Order.java
  mission1/src/main/java/com/example/mission1/domain/OrderId.java
  mission1/src/main/java/com/example/mission1/repository/CustomerRepository.java
  mission1/src/main/java/com/example/mission1/repository/OrderRepository.java
  mission1/src/main/resources/application.yaml
  mission1/src/test/java/com/example/mission1/Mission1ApplicationTests.java
  mission1/src/test/java/com/example/mission1/domain/CustomerTest.java
  mission1/src/test/java/com/example/mission1/repository/CustomerRepositoryTest.java
  mission1/src/test/java/com/example/mission1/repository/OrderRepositoryTest.java
  mission2/.gitignore
  mission2/.mvn/wrapper/maven-wrapper.jar
  mission2/.mvn/wrapper/maven-wrapper.properties
  mission2/mvnw
  mission2/mvnw.cmd
  mission2/pom.xml
  mission2/src/main/java/com/example/mission2/Mission2Application.java
  mission2/src/main/java/com/example/mission2/config/DataSourceConfig.java
  mission2/src/main/java/com/example/mission2/domain/Customer.java
  mission2/src/main/resources/application.yaml
  mission2/src/test/java/com/example/mission2/Mission2ApplicationTests.java
  mission2/src/test/java/com/example/mission2/PersistenceContextTest.java
  mission3/.gitignore
  mission3/.mvn/wrapper/maven-wrapper.jar
  mission3/.mvn/wrapper/maven-wrapper.properties
  mission3/mvnw
  mission3/mvnw.cmd
  mission3/pom.xml
  mission3/src/main/java/com/example/mission3/Mission3Application.java
  mission3/src/main/java/com/example/mission3/domain/BaseEntity.java
  mission3/src/main/java/com/example/mission3/domain/Drink.java
  mission3/src/main/java/com/example/mission3/domain/Food.java
  mission3/src/main/java/com/example/mission3/domain/Item.java
  mission3/src/main/java/com/example/mission3/domain/Order.java
  mission3/src/main/java/com/example/mission3/domain/OrderItem.java
  mission3/src/main/java/com/example/mission3/domain/OrderStatus.java
  mission3/src/main/java/com/example/mission3/repository/ItemRepository.java
  mission3/src/main/java/com/example/mission3/repository/OrderRepository.java
  mission3/src/main/resources/application.yaml
  mission3/src/test/java/com/example/mission3/Mission3ApplicationTests.java
  mission3/src/test/java/com/example/mission3/repository/ItemRepositoryTest.java
  mission3/src/test/java/com/example/mission3/repository/OrderRepositoryTest.java
Labels: Team-Blackdog, 🔥 매운맛

#183 [3기-C 권주성] Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/kwonjoosung/springbootjpa/SpringBootJpaApplication.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/Customer.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/programmers/kwonjoosung/springbootjpa/SpringBootJpaApplicationTests.java
  src/test/java/com/programmers/kwonjoosung/springbootjpa/model/CustomerTest.java
  src/test/java/com/programmers/kwonjoosung/springbootjpa/repository/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-R

#195 [3기-C 최은비] Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/jpaproject/JpaProjectApplication.java
  src/main/java/com/kdt/jpaproject/config/DataSourceConfig.java
  src/main/java/com/kdt/jpaproject/domain/Customer.java
  src/main/java/com/kdt/jpaproject/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/jpaproject/JpaProjectApplicationTests.java
  src/test/java/com/kdt/jpaproject/domain/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-R

#189 [3기-C 복신영] Mission 1-2: JPA 소개/영속성 컨텍스트
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kdt/springbootjpa/SpringbootJpaApplication.java
  src/main/java/kdt/springbootjpa/customer/entity/Customer.java
  src/main/java/kdt/springbootjpa/customer/repository/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/kdt/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/kdt/springbootjpa/customer/CustomerPersistenceTest.java
  src/test/java/kdt/springbootjpa/customer/CustomerRepositoryTest.java
  src/test/java/kdt/springbootjpa/customer/CustomerTest.java
  src/test/resources/application.yml
Labels: Team-R

#185 [3기-C 권주성] Mission 2: 영속성 컨텍스트
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/kwonjoosung/springbootjpa/SpringBootJpaApplication.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/BaseEntity.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/Customer.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/Item.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/Keyboard.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/KeyboardType.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/Member.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/Mouse.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/MouseType.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/Order.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/OrderItem.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/model/OrderStatus.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/repository/CustomerRepository.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/repository/MemberRepository.java
  src/main/java/com/programmers/kwonjoosung/springbootjpa/repository/OrderRepository.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/test/java/com/programmers/kwonjoosung/springbootjpa/OrderFlowTest.java
  src/test/java/com/programmers/kwonjoosung/springbootjpa/SpringBootJpaApplicationTests.java
  src/test/java/com/programmers/kwonjoosung/springbootjpa/model/CustomerTest.java
  src/test/java/com/programmers/kwonjoosung/springbootjpa/model/PersistenceContextTest.java
  src/test/java/com/programmers/kwonjoosung/springbootjpa/repository/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-R

#187 [3기-C 이수영] Mission 1: JPA 소개
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/com/prgrms/be/jpa/PrgrmsJpaApplication.java
  src/main/java/com/prgrms/be/jpa/domain/Customer.java
  src/main/java/com/prgrms/be/jpa/domain/order/BaseEntity.java
  src/main/java/com/prgrms/be/jpa/domain/order/Car.java
  src/main/java/com/prgrms/be/jpa/domain/order/Food.java
  src/main/java/com/prgrms/be/jpa/domain/order/Furniture.java
  src/main/java/com/prgrms/be/jpa/domain/order/Item.java
  src/main/java/com/prgrms/be/jpa/domain/order/Member.java
  src/main/java/com/prgrms/be/jpa/domain/order/Order.java
  src/main/java/com/prgrms/be/jpa/domain/order/OrderItem.java
  src/main/java/com/prgrms/be/jpa/domain/order/OrderStatus.java
  src/main/java/com/prgrms/be/jpa/repository/CustomerRepository.java
  src/main/java/com/prgrms/be/jpa/repository/MemberRepository.java
  src/main/java/com/prgrms/be/jpa/repository/OrderRepository.java
  src/main/resources/application.yaml
  src/test/java/com/prgrms/be/jpa/PersistenceContextTest.java
  src/test/java/com/prgrms/be/jpa/domain/CustomerTest.java
  src/test/java/com/prgrms/be/jpa/domain/order/OrderPersistenceTest.java
  src/test/java/com/prgrms/be/jpa/repository/CustomerRepositoryTest.java
  src/test/java/com/prgrms/be/jpa/repository/OrderRepositoryTest.java
Labels: Team-Marco, 🔥 매운맛

#212 [3기-C 서예원]Mission 3: 연관관계 매핑
  .gitignore
  pom.xml
  src/main/java/com/kdt/lecture/JpaOrderSystem.java
  src/main/java/com/kdt/lecture/config/DataSourceConfig.java
  src/main/java/com/kdt/lecture/domain/BaseEntity.java
  src/main/java/com/kdt/lecture/domain/member/Member.java
  src/main/java/com/kdt/lecture/domain/member/MemberRepository.java
  src/main/java/com/kdt/lecture/domain/order/Item.java
  src/main/java/com/kdt/lecture/domain/order/Order.java
  src/main/java/com/kdt/lecture/domain/order/OrderItem.java
  src/main/java/com/kdt/lecture/domain/order/OrderRepository.java
  src/main/java/com/kdt/lecture/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/com/kdt/lecture/JpaOrderSystemTest.java
  src/test/java/com/kdt/lecture/domain/member/MemberRepositoryTest.java
Labels: 🔥 매운맛, Team-Allen
