Repository prgrms-be-devcourse/springboot-jpa, pull requests merged in 2023-07, with the labels that each got.

#223 [4기] 최성원 Init project, 도메인 생성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/mission1/Mission1Application.java
  src/main/java/com/kdt/mission1/domain/Customer.java
  src/main/resources/application.yml
Labels: Team-Ray, 🔥 매운맛

#225 [4기 최지연] Mission1 : 프로젝트 생성 및 엔티티 생성
  study-jpa/.gitignore
  study-jpa/.mvn/wrapper/maven-wrapper.jar
  study-jpa/.mvn/wrapper/maven-wrapper.properties
  study-jpa/mvnw
  study-jpa/mvnw.cmd
  study-jpa/pom.xml
  study-jpa/src/main/java/org/prgrms/studyjpa/StudyJpaApplication.java
  study-jpa/src/main/java/org/prgrms/studyjpa/domain/Customer.java
Labels: Team-Ray, 🔥 매운맛

#224 [4기-이홍섭] Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/example/springbootjpa/domain/Customer.java
  src/main/java/com/example/springbootjpa/domain/CustomerRepository.java
  src/main/java/com/example/springbootjpa/golbal/ErrorCode.java
  src/main/java/com/example/springbootjpa/golbal/exception/DomainException.java
  src/main/resources/application.properties
  src/test/java/com/example/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/example/springbootjpa/domain/CustomerRepositoryTest.java
  src/test/java/com/example/springbootjpa/domain/CustomerTest.java
  src/test/resources/application.yml
Labels: Team-F, 🔥 매운맛

#228 [4기 황준호] JPA : Mission 1 제출입니다.
  kdt-jpa/.gitignore
  kdt-jpa/build.gradle
  kdt-jpa/settings.gradle
  kdt-jpa/src/main/java/com/kdt/kdtjpa/KdtJpaApplication.java
  kdt-jpa/src/main/java/com/kdt/kdtjpa/config/DataSourceConfig.java
  kdt-jpa/src/main/java/com/kdt/kdtjpa/domain/Customer.java
  kdt-jpa/src/main/java/com/kdt/kdtjpa/domain/CustomerRepository.java
  kdt-jpa/src/main/java/com/kdt/kdtjpa/domain/Name.java
  kdt-jpa/src/main/resources/application.yml
  kdt-jpa/src/test/java/com/kdt/kdtjpa/domain/JPATest.java
  kdt-jpa/src/test/java/com/kdt/kdtjpa/domain/NameTest.java
Labels: Team-Ray, 🔥 매운맛

#226 [4기] 최성원 - Jpa 레포 구현, Customer getter 추가, DB 작동 시험 테스트
  src/main/java/com/kdt/mission1/domain/Customer.java
  src/main/java/com/kdt/mission1/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/kdt/mission1/domain/CustomerRepositoryTest.java
  src/test/resources/application.yml
Labels: Team-Ray, 🔥 매운맛

#231 [4기 - 김혜민] Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/programmers/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/programmers/springbootjpa/domain/Customer.java
  src/main/java/com/programmers/springbootjpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/programmers/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/programmers/springbootjpa/domain/CustomerRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/CustomerTest.java
Labels: Team-F, 🔥 매운맛

#250 [4기 박현지] 프로젝트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/prgms/springbootjpa/SpringbootJpaApplication.java
Labels: Team-Ray, 🔥 매운맛

#248 [4기 고예성] Mission 1 PR 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kr/co/prgrms/jpaintro/JpaIntroApplication.java
  src/main/java/kr/co/prgrms/jpaintro/config/DataSourceConfig.java
  src/main/java/kr/co/prgrms/jpaintro/domain/Customer.java
  src/main/java/kr/co/prgrms/jpaintro/domain/CustomerRepository.java
  src/main/java/kr/co/prgrms/jpaintro/exception/IllegalNameException.java
  src/main/resources/application.yml
  src/test/java/kr/co/prgrms/jpaintro/JpaIntroApplicationTests.java
  src/test/java/kr/co/prgrms/jpaintro/domain/CustomerRepositoryTest.java
Labels: Team-F, 🔥 매운맛

#234 [4기 최지연] Mission1 : CustomerRepository 추가 및 테스트 코드 작성
  study-jpa/pom.xml
  study-jpa/src/main/java/org/prgrms/studyjpa/domain/Customer.java
  study-jpa/src/main/java/org/prgrms/studyjpa/domain/CustomerRepository.java
  study-jpa/src/main/resources/application.yaml
  study-jpa/src/test/java/org/prgrms/studyjpa/domain/CustomerRepositoryTest.java
Labels: Team-Ray, 🔥 매운맛

#265 [4기 최성원] - 엔티티 생명주기 연습
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/mission1/Mission1Application.java
  src/main/java/com/kdt/mission1/domain/Customer.java
  src/main/java/com/kdt/mission1/domain/CustomerRepository.java
  src/test/java/com/kdt/mission1/domain/CustomerRepositoryTest.java
  src/test/java/com/kdt/mission1/domain/PersistenceContextTest.java
  src/test/resources/application.yml
Labels: Team-Ray, 🔥 매운맛

#240 [4기 황준호] JPA - Mission 2 제출합니다.
  kdt-jpa/README.md
  kdt-jpa/src/main/java/com/kdt/kdtjpa/domain/Customer.java
  kdt-jpa/src/main/java/com/kdt/kdtjpa/domain/Name.java
  kdt-jpa/src/test/java/com/kdt/kdtjpa/domain/JPATest.java
  kdt-jpa/src/test/java/com/kdt/kdtjpa/domain/PersistenceContextTest.java
Labels: Team-Ray, 🔥 매운맛

#253 [4기 김범우] Mission 2 : 영속성 컨텍스트
  src/test/java/com/lecture/jpa/domain/PersistenceContextTest.java
Labels: Team-Ray, 🔥 매운맛

#278 [4기 최성원] - 이전 미션과정 불러오기
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/mission1/Mission1Application.java
  src/main/java/com/kdt/mission1/domain/Customer.java
  src/main/java/com/kdt/mission1/domain/CustomerRepository.java
  src/test/java/com/kdt/mission1/domain/CustomerRepositoryTest.java
  src/test/java/com/kdt/mission1/domain/PersistenceContextTest.java
  src/test/resources/application.yml
Labels: Team-Ray, 🔥 매운맛

#264 [4기 한승원] Mission 1 PR 제출합니다
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/devcourse/springbootjpa/CustomerRepository.java
  src/main/java/com/devcourse/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/devcourse/springbootjpa/domain/Customer.java
  src/main/java/com/devcourse/springbootjpa/exception/InvalidCustomerException.java
  src/main/resources/application.yaml
  src/test/java/com/devcourse/springbootjpa/CustomerRepositoryTest.java
  src/test/java/com/devcourse/springbootjpa/CustomerTest.java
  src/test/java/com/devcourse/springbootjpa/PersistenceContextTest.java
Labels: Team-F, 🔥 매운맛

#227 [4기] 주홍석 - Customer 모델 생성 및 테스트 진행
  src/main/java/com/jhs/springbootjpa/model/Customer.java
  src/test/java/com/jhs/springbootjpa/model/CustomerTest.java
Labels: Team-Ray, 🔥 매운맛

#254 [4기 장수연]Mission 1: JPA 소개
  .gitignore
  .gradle/8.1.1/checksums/checksums.lock
  .gradle/8.1.1/checksums/md5-checksums.bin
  .gradle/8.1.1/checksums/sha1-checksums.bin
  .gradle/8.1.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.1.1/dependencies-accessors/gc.properties
  .gradle/8.1.1/executionHistory/executionHistory.bin
  .gradle/8.1.1/executionHistory/executionHistory.lock
  .gradle/8.1.1/fileChanges/last-build.bin
  .gradle/8.1.1/fileHashes/fileHashes.bin
  .gradle/8.1.1/fileHashes/fileHashes.lock
  .gradle/8.1.1/fileHashes/resourceHashesCache.bin
  .gradle/8.1.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/vcs-1/gc.properties
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/kdtjpa/KdtJpaApplication.java
  src/main/java/com/example/kdtjpa/config/DataSourceConfig.java
  src/main/java/com/example/kdtjpa/domain/Customer.java
  src/main/java/com/example/kdtjpa/domain/CustomerRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/kdtjpa/KdtJpaApplicationTests.java
  src/test/java/com/example/kdtjpa/domain/CustomerRepositoryTest.java
Labels: Team-Kyu, 💧 순한맛

#252 [4기 신범철] Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/jpa_mission/JpaMissionApplication.java
  src/main/java/com/programmers/jpa_mission/config/DataSourceConfig.java
  src/main/java/com/programmers/jpa_mission/domain/Customer.java
  src/main/java/com/programmers/jpa_mission/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/programmers/jpa_mission/JpaMissionApplicationTests.java
  src/test/java/com/programmers/jpa_mission/domain/CustomerRepositoryTest.java
  src/test/java/com/programmers/jpa_mission/domain/CustomerTest.java
Labels: Team-Kyu, 🔥 매운맛

#274 [4기 오세한] Mission 2: 영속성 컨텍스트
  .gitignore
  HELP.md
  build.gradle
  build/reports/tests/test/classes/prgms.jpamission2.persistenceTest.PersistenceContextTest.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/prgms.jpamission2.persistenceTest.html
  build/resources/main/application.yaml
  build/test-results/test/TEST-prgms.jpamission2.persistenceTest.PersistenceContextTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/compileTransaction/stash-dir/DataSourceConfig.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/compileTransaction/stash-dir/PersistenceContextTest.class.uniqueId0
  build/tmp/compileTestJava/previous-compilation-data.bin
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/prgms/jpamission2/JpaMission2Application.java
  src/main/java/prgms/jpamission2/config/DataSourceConfig.java
  src/main/java/prgms/jpamission2/config/domain/Customer.java
  src/main/java/prgms/jpamission2/config/domain/CustomerRepository.java
  src/main/java/prgms/jpamission2/config/domain/order/Member.java
  src/main/resources/application.yaml
  src/test/java/prgms/jpamission2/JpaMission2ApplicationTests.java
  src/test/java/prgms/jpamission2/persistenceTest/PersistenceContextTest.java
Labels: Team-Kyu, 🔥 매운맛

#251 [4기 오세한] Mission 1: JPA 소개
  .gitignore
  HELP.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/prgms/jpa_w1/JpaW1Application.java
  src/main/java/prgms/jpa_w1/config/DataSourceConfig.java
  src/main/java/prgms/jpa_w1/config/domain/Customer.java
  src/main/java/prgms/jpa_w1/config/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/prgms/jpa_w1/JpaW1ApplicationTests.java
  src/test/java/prgms/jpa_w1/domain/CustomerRepositoryTest.java
Labels: Team-Kyu, 🔥 매운맛

#239 [4기 최성원] - update 테스트, dirty checking 실제 확인
  src/main/java/com/kdt/mission1/domain/Customer.java
  src/test/java/com/kdt/mission1/domain/CustomerRepositoryTest.java
  src/test/resources/application.yml
Labels: Team-Ray, 🔥 매운맛

#271 [4기 장수연] Mission 2: 영속성 컨텍스트
  src/main/java/com/example/kdtjpa/domain/Customer.java
  src/test/java/com/example/kdtjpa/domain/PersistenceContextTest.java
Labels: Team-Kyu, 💧 순한맛

#282 [4기] 주홍석 Mission 1 CRUD 실습
  src/main/java/com/jhs/springbootjpa/model/Customer.java
  src/main/java/com/jhs/springbootjpa/repository/CustomerRepository.java
  src/test/java/com/jhs/springbootjpa/repository/CustomerRepositoryTest.java
  src/test/resources/application.yml
Labels: Team-Ray, 🔥 매운맛

#249 [4기 신예진] Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/weeklyjpa/WeeklyJpaApplication.java
  src/main/java/com/example/weeklyjpa/config/DataSourceConfig.java
  src/main/java/com/example/weeklyjpa/domain/Customer.java
  src/main/java/com/example/weeklyjpa/domain/CustomerRepository.java
  src/main/resources/application.properties
  src/test/java/com/example/weeklyjpa/WeeklyJpaApplicationTests.java
  src/test/java/com/example/weeklyjpa/domain/CustomerRepositoryTest.java
  src/test/java/com/example/weeklyjpa/domain/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-HiHi

#238 [4기 정성현] Mission 1 PR 제출합니다.
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/me/kimihiqq/springbootjpa/SpringbootJpaApplication.java
  src/main/java/me/kimihiqq/springbootjpa/domain/customer/Customer.java
  src/main/java/me/kimihiqq/springbootjpa/domain/customer/CustomerRepository.java
  src/main/java/me/kimihiqq/springbootjpa/exception/InvalidNameException.java
  src/main/resources/application.yml
  src/test/java/me/kimihiqq/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/me/kimihiqq/springbootjpa/domain/customer/CustomerRepositoryTest.java
Labels: Team-F, 🔥 매운맛

#281 [4기 이근우] Mission 2, 3 PR 제출합니다.
  src/main/java/com/springbootjpa/domain/Delivery.java
  src/main/java/com/springbootjpa/domain/Item.java
  src/main/java/com/springbootjpa/domain/ItemRepository.java
  src/main/java/com/springbootjpa/domain/Name.java
  src/main/java/com/springbootjpa/domain/Order.java
  src/main/java/com/springbootjpa/domain/OrderItem.java
  src/main/java/com/springbootjpa/domain/OrderRepository.java
  src/main/java/com/springbootjpa/exception/InValidCustomerException.java
  src/main/java/com/springbootjpa/exception/InValidItemException.java
  src/main/java/com/springbootjpa/exception/InValidOrderItemException.java
  src/main/java/com/springbootjpa/exception/NoValidCustomerException.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/springbootjpa/domain/CustomerTest.java
  src/test/java/com/springbootjpa/domain/ItemTest.java
  src/test/java/com/springbootjpa/domain/LifeCycleTest.java
  src/test/java/com/springbootjpa/domain/NameTest.java
  src/test/java/com/springbootjpa/domain/OrderItemTest.java
  src/test/java/com/springbootjpa/domain/OrderRepositoryTest.java
Labels: Team-F, 🔥 매운맛

#298 [4기 김혜민] Mission 2, 3 PR 제출합니다.
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/programmers/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/programmers/springbootjpa/domain/customer/Customer.java
  src/main/java/com/programmers/springbootjpa/domain/customer/CustomerRepository.java
  src/main/java/com/programmers/springbootjpa/domain/order/BaseEntity.java
  src/main/java/com/programmers/springbootjpa/domain/order/Car.java
  src/main/java/com/programmers/springbootjpa/domain/order/Food.java
  src/main/java/com/programmers/springbootjpa/domain/order/Furniture.java
  src/main/java/com/programmers/springbootjpa/domain/order/Item.java
  src/main/java/com/programmers/springbootjpa/domain/order/ItemRepository.java
  src/main/java/com/programmers/springbootjpa/domain/order/Member.java
  src/main/java/com/programmers/springbootjpa/domain/order/MemberRepository.java
  src/main/java/com/programmers/springbootjpa/domain/order/Order.java
  src/main/java/com/programmers/springbootjpa/domain/order/OrderItem.java
  src/main/java/com/programmers/springbootjpa/domain/order/OrderItemRepository.java
  src/main/java/com/programmers/springbootjpa/domain/order/OrderRepository.java
  src/main/java/com/programmers/springbootjpa/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/com/programmers/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/programmers/springbootjpa/domain/PersistenceContextTest.java
  src/test/java/com/programmers/springbootjpa/domain/customer/CustomerRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/customer/CustomerTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/CarTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/FoodTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/FurnitureTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/ItemRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/MemberRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/MemberTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/OrderItemTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/OrderRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/order/OrderTest.java
Labels: Team-F, 🔥 매운맛

#272 [4기 김영명] Weekely Mission 1,3 PR 제출합니다
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/kdt/weeklyjpa/WeeklyJpaApplication.java
  src/main/java/com/kdt/weeklyjpa/config/DataSourceConfig.java
  src/main/java/com/kdt/weeklyjpa/domain/customer/Customer.java
  src/main/java/com/kdt/weeklyjpa/domain/customer/CustomerRepository.java
  src/main/java/com/kdt/weeklyjpa/domain/item/Item.java
  src/main/java/com/kdt/weeklyjpa/domain/item/ItemRepository.java
  src/main/java/com/kdt/weeklyjpa/domain/order/Order.java
  src/main/java/com/kdt/weeklyjpa/domain/order/OrderRepository.java
  src/main/java/com/kdt/weeklyjpa/domain/order/OrderStatus.java
  src/main/java/com/kdt/weeklyjpa/domain/orderitem/OrderItem.java
  src/main/resources/application.yml
  src/test/java/com/kdt/weeklyjpa/domain/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Joseph

#287 [4기 한승원] Mission 2,3 PR 제출합니다
  src/main/java/com/devcourse/springbootjpa/CustomerRepository.java
  src/main/java/com/devcourse/springbootjpa/domain/Customer.java
  src/main/java/com/devcourse/springbootjpa/domain/order/Item.java
  src/main/java/com/devcourse/springbootjpa/domain/order/Member.java
  src/main/java/com/devcourse/springbootjpa/domain/order/Order.java
  src/main/java/com/devcourse/springbootjpa/domain/order/OrderItem.java
  src/main/java/com/devcourse/springbootjpa/domain/order/OrderStatus.java
  src/main/java/com/devcourse/springbootjpa/domain/repository/ItemRepository.java
  src/main/java/com/devcourse/springbootjpa/domain/repository/MemberRepository.java
  src/main/java/com/devcourse/springbootjpa/domain/repository/OrderItemRepository.java
  src/main/java/com/devcourse/springbootjpa/domain/repository/OrderRepository.java
  src/main/java/com/devcourse/springbootjpa/exception/InvalidCustomerException.java
  src/main/java/com/devcourse/springbootjpa/exception/InvalidQuantityException.java
  src/test/java/com/devcourse/springbootjpa/CustomerRepositoryTest.java
  src/test/java/com/devcourse/springbootjpa/CustomerTest.java
  src/test/java/com/devcourse/springbootjpa/ItemTest.java
  src/test/java/com/devcourse/springbootjpa/OrderPersistenceTest.java
  src/test/java/com/devcourse/springbootjpa/OrderTest.java
  src/test/java/com/devcourse/springbootjpa/PersistenceContextTest.java
Labels: Team-F, 🔥 매운맛

#229 [4기 박이슬] Mission 1: JPA 소개
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/jpa/JpaApplication.java
  src/main/java/com/programmers/jpa/domain/Customer.java
  src/main/java/com/programmers/jpa/domain/CustomerRepository.java
  src/main/java/com/programmers/jpa/domain/Item.java
  src/main/java/com/programmers/jpa/domain/Member.java
  src/main/java/com/programmers/jpa/domain/Order.java
  src/main/java/com/programmers/jpa/domain/OrderItem.java
  src/main/java/com/programmers/jpa/domain/OrderStatus.java
  src/test/java/com/programmers/jpa/JpaApplicationTests.java
  src/test/java/com/programmers/jpa/domain/CustomerRepositoryTest.java
  src/test/java/com/programmers/jpa/domain/OrderPersistenceTest.java
  src/test/java/com/programmers/jpa/domain/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-HiHi

#301 [4기 고예성] Mission 2,3 PR 제출합니다
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kr/co/prgrms/jpaintro/JpaIntroApplication.java
  src/main/java/kr/co/prgrms/jpaintro/config/DataSourceConfig.java
  src/main/java/kr/co/prgrms/jpaintro/domain/customer/Customer.java
  src/main/java/kr/co/prgrms/jpaintro/domain/customer/CustomerRepository.java
  src/main/java/kr/co/prgrms/jpaintro/domain/item/Car.java
  src/main/java/kr/co/prgrms/jpaintro/domain/item/Food.java
  src/main/java/kr/co/prgrms/jpaintro/domain/item/Furniture.java
  src/main/java/kr/co/prgrms/jpaintro/domain/item/Item.java
  src/main/java/kr/co/prgrms/jpaintro/domain/item/ItemRepository.java
  src/main/java/kr/co/prgrms/jpaintro/domain/order/Order.java
  src/main/java/kr/co/prgrms/jpaintro/domain/order/OrderItem.java
  src/main/java/kr/co/prgrms/jpaintro/domain/order/OrderItemRepository.java
  src/main/java/kr/co/prgrms/jpaintro/domain/order/OrderRepository.java
  src/main/java/kr/co/prgrms/jpaintro/domain/order/OrderStatus.java
  src/main/java/kr/co/prgrms/jpaintro/exception/IllegalNameException.java
  src/main/java/kr/co/prgrms/jpaintro/exception/IllegalValueException.java
  src/main/resources/application.yml
  src/test/java/kr/co/prgrms/jpaintro/JpaIntroApplicationTests.java
  src/test/java/kr/co/prgrms/jpaintro/PersistenceContextTest.java
  src/test/java/kr/co/prgrms/jpaintro/domain/CustomerRepositoryTest.java
  src/test/java/kr/co/prgrms/jpaintro/domain/order/OrderRepositoryTest.java
Labels: Team-F, 🔥 매운맛

#296 [4기 정성현] Mission 2,3 PR 제출합니다
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/me/kimihiqq/springbootjpa/SpringbootJpaApplication.java
  src/main/java/me/kimihiqq/springbootjpa/domain/customer/Customer.java
  src/main/java/me/kimihiqq/springbootjpa/domain/order/Item.java
  src/main/java/me/kimihiqq/springbootjpa/domain/order/Member.java
  src/main/java/me/kimihiqq/springbootjpa/domain/order/Order.java
  src/main/java/me/kimihiqq/springbootjpa/domain/order/OrderItem.java
  src/main/java/me/kimihiqq/springbootjpa/domain/order/OrderStatus.java
  src/main/java/me/kimihiqq/springbootjpa/domain/repository/CustomerRepository.java
  src/main/java/me/kimihiqq/springbootjpa/domain/repository/ItemRepository.java
  src/main/java/me/kimihiqq/springbootjpa/domain/repository/MemberRepository.java
  src/main/java/me/kimihiqq/springbootjpa/domain/repository/OrderItemRepository.java
  src/main/java/me/kimihiqq/springbootjpa/domain/repository/OrderRepository.java
  src/main/java/me/kimihiqq/springbootjpa/exception/InvalidNameException.java
  src/main/resources/application.yml
  src/test/java/me/kimihiqq/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/me/kimihiqq/springbootjpa/domain/customer/CustomerRepositoryTest.java
  src/test/java/me/kimihiqq/springbootjpa/domain/order/OrderPersistenceTest.java
Labels: Team-F, 🔥 매운맛
