Repository prgrms-be-devcourse/springboot-jpa, pull requests merged in 2023-09, with the labels that each got.

#243 [4기-C 구범모] Mission 1: JPA 소개
  kdt-spring-jpa/.gitignore
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/KdtSpringJpaApplication.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/config/DataSourceConfig.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/Customer.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/CustomerRepository.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/order/Car.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/order/Food.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/order/Furniture.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/order/Item.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/order/Member.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/order/Order.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/order/OrderItem.java
  kdt-spring-jpa/src/main/java/com/example/kdt/spring/jpa/domain/order/OrderStatus.java
  kdt-spring-jpa/src/test/java/com/example/kdt/spring/jpa/domain/CustomerRepositoryTest.java
  kdt-spring-jpa/src/test/java/com/example/kdt/spring/jpa/domain/order/CustomerRepositoryTest.java
  kdt-spring-jpa/src/test/java/com/example/kdt/spring/jpa/domain/order/RelationTest.java
Labels: 💧 순한맛, Team-HiHi

#294 [4기 신예진] Mission 3 제출합니다 !
  build.gradle
  src/main/java/com/example/weeklyjpa/domain/item/Book.java
  src/main/java/com/example/weeklyjpa/domain/item/Item.java
  src/main/java/com/example/weeklyjpa/domain/item/OrderItem.java
  src/main/java/com/example/weeklyjpa/domain/item/Phone.java
  src/main/java/com/example/weeklyjpa/domain/member/Member.java
  src/main/java/com/example/weeklyjpa/domain/order/Order.java
  src/main/java/com/example/weeklyjpa/repository/CustomerRepository.java
  src/main/java/com/example/weeklyjpa/utils/OrderStatus.java
  src/main/resources/application.properties
  src/test/java/com/example/weeklyjpa/domain/CustomerRepositoryTest.java
  src/test/java/com/example/weeklyjpa/domain/OrderPersistenceTest.java
  src/test/java/com/example/weeklyjpa/domain/PersistenceContextTest.java
Labels: Team-HiHi

#260 [4기 최준혁] Mission 1, 3: JPA 소개
  jpastudy/.gitignore
  jpastudy/build.gradle
  jpastudy/gradle/wrapper/gradle-wrapper.jar
  jpastudy/gradle/wrapper/gradle-wrapper.properties
  jpastudy/gradlew
  jpastudy/gradlew.bat
  jpastudy/settings.gradle
  jpastudy/src/main/java/com/programmers/june/jpastudy/JpastudyApplication.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/customer/entity/Customer.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/customer/repository/CustomerRepository.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/item/entity/Item.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/item/repository/ItemRepository.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/order/entity/Order.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/order/repository/OrderRepository.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/order/service/OrderService.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/order_item/entity/OrderItem.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/order_item/model/OrderStatus.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/domain/order_item/repository/OrderItemRepository.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/global/BaseEntity.java
  jpastudy/src/main/java/com/programmers/june/jpastudy/global/config/JpaAuditingConfig.java
  jpastudy/src/main/resources/application.yml
  jpastudy/src/test/java/com/programmers/june/jpastudy/JpastudyApplicationTests.java
  jpastudy/src/test/java/com/programmers/june/jpastudy/domain/CustomerRepositoryTest.java
  jpastudy/src/test/java/com/programmers/june/jpastudy/domain/order/service/OrderServiceTest.java
Labels: 💧 순한맛, 🔥 매운맛, Team-HiHi

#325 [4기 강병곤] Mission 3: 연관관계 매핑
  src/main/java/com/kdt/lecturejpa/config/DataSourceConfig.java
  src/main/java/com/kdt/lecturejpa/domain/Customer.java
  src/main/java/com/kdt/lecturejpa/domain/item/Item.java
  src/main/java/com/kdt/lecturejpa/domain/item/ItemRepository.java
  src/main/java/com/kdt/lecturejpa/domain/member/Member.java
  src/main/java/com/kdt/lecturejpa/domain/member/MemberRepository.java
  src/main/java/com/kdt/lecturejpa/domain/order/Order.java
  src/main/java/com/kdt/lecturejpa/domain/order/OrderRepository.java
  src/main/java/com/kdt/lecturejpa/domain/order/OrderService.java
  src/main/java/com/kdt/lecturejpa/domain/order/OrderStatus.java
  src/main/java/com/kdt/lecturejpa/domain/order_item/OrderItem.java
  src/main/java/com/kdt/lecturejpa/domain/order_item/OrderItemRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/lecturejpa/domain/PersistenceContextTest.java
  src/test/java/com/kdt/lecturejpa/domain/order/OrderPersistenceTest.java
  src/test/java/com/kdt/lecturejpa/domain/order/OrderServiceTest.java
Labels: 🔥 매운맛, Team-HiHi

#327 [4기 박이슬] Mission 3: 연관관계 매핑
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/com/programmers/jpa/domain/order/BaseEntity.java
  src/main/java/com/programmers/jpa/domain/order/Car.java
  src/main/java/com/programmers/jpa/domain/order/Food.java
  src/main/java/com/programmers/jpa/domain/order/Furniture.java
  src/main/java/com/programmers/jpa/domain/order/Item.java
  src/main/java/com/programmers/jpa/domain/order/ItemType.java
  src/main/java/com/programmers/jpa/domain/order/Member.java
  src/main/java/com/programmers/jpa/domain/order/Order.java
  src/main/java/com/programmers/jpa/domain/order/OrderItem.java
  src/main/java/com/programmers/jpa/domain/order/OrderRepository.java
  src/main/java/com/programmers/jpa/domain/order/OrderStatus.java
  src/main/java/com/programmers/jpa/order/ApiResponse.java
  src/main/java/com/programmers/jpa/order/controller/OrderController.java
  src/main/java/com/programmers/jpa/order/converter/OrderConverter.java
  src/main/java/com/programmers/jpa/order/dto/ItemDto.java
  src/main/java/com/programmers/jpa/order/dto/MemberDto.java
  src/main/java/com/programmers/jpa/order/dto/OrderDto.java
  src/main/java/com/programmers/jpa/order/dto/OrderItemDto.java
  src/main/java/com/programmers/jpa/order/service/OrderService.java
Labels: 🔥 매운맛, Team-HiHi
