Repository prgrms-be-devcourse/springboot-jpa, pull requests merged in 2023-08, with the labels that each got.

#293 [4기 이성주] Mission1 제출입니다.
  build.gradle
  src/main/java/prgrms/lecture/jpa/JpaApplication.java
  src/main/java/prgrms/lecture/jpa/config/DataSourceConfig.java
  src/main/java/prgrms/lecture/jpa/domain/Customer.java
  src/main/java/prgrms/lecture/jpa/domain/CustomerRepository.java
  src/test/java/prgrms/lecture/jpa/domain/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Navy

#284 [4기 문종운, 김재웅] Mission 1 PR 제출합니다.
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/jpa.main.iml
  .idea/modules/jpa.test.iml
  .idea/vcs.xml
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/pgms/jpa/JpaApplication.java
  src/main/java/com/pgms/jpa/domain/Customer.java
  src/main/java/com/pgms/jpa/domain/CustomerRepository.java
  src/main/java/com/pgms/jpa/domain/DefaultCustomerRepository.java
  src/main/java/com/pgms/jpa/global/ErrorCode.java
  src/main/java/com/pgms/jpa/service/CustomerService.java
  src/test/java/com/pgms/jpa/JpaApplicationTests.java
  src/test/java/com/pgms/jpa/domain/CustomerCrudTest.java
Labels: 🔥 매운맛, Team-Allen

#280 [4기 황창현, 이현호] JPA Mission 2 - 영속성 컨텍스트 생명주기 실습
  src/main/java/com/programmers/springbootjpa/domain/Address.java
  src/test/java/com/programmers/springbootjpa/PersistenceContextTest.java
  src/test/java/com/programmers/springbootjpa/SpringbootJpaApplicationTests.java
Labels: Team-Tyler, 🔥 매운맛

#246 [4기 강병곤] Mission 1: JPA 소개
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/kdt/lecturejpa/LectureJpaApplication.java
  src/main/java/com/kdt/lecturejpa/config/DataSourceConfig.java
  src/main/java/com/kdt/lecturejpa/domain/Customer.java
  src/main/java/com/kdt/lecturejpa/domain/CustomerRepository.java
  src/main/resources/application.yaml
  src/test/java/com/kdt/lecturejpa/LectureJpaApplicationTests.java
  src/test/java/com/kdt/lecturejpa/domain/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-HiHi

#279 [4기 최성원] 기본 엔티티 작성
  src/main/java/com/kdt/mission1/domain/order/Item.java
  src/main/java/com/kdt/mission1/domain/order/Member.java
  src/main/java/com/kdt/mission1/domain/order/Order.java
  src/main/java/com/kdt/mission1/domain/order/OrderItem.java
  src/main/java/com/kdt/mission1/domain/order/OrderStatus.java
Labels: Team-Ray, 🔥 매운맛

#291 [4기 문희조] Mission 1, 2, 3 PR 제출
  .gitignore
  README.md
  build.gradle
  docs/README.md
  docs/mission1.md
  docs/mission2.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/SpringbootJpaApplication.java
  src/main/java/com/kdt/global/config/DataSourceConfig.java
  src/main/java/com/kdt/global/exception/GlobalExceptionHandler.java
  src/main/java/com/kdt/module/customer/domain/Customer.java
  src/main/java/com/kdt/module/customer/domain/repository/CustomerRepository.java
  src/main/java/com/kdt/module/customer/domain/repository/CustomerRepositoryCustom.java
  src/main/java/com/kdt/module/customer/domain/repository/EntityMangerCallback.java
  src/main/java/com/kdt/module/customer/domain/repository/JpaTemplate.java
  src/main/java/com/kdt/module/item/Item.java
  src/main/java/com/kdt/module/order/Order.java
  src/main/java/com/kdt/module/order/OrderItem.java
  src/main/java/com/kdt/module/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/com/kdt/module/customer/domain/repository/CustomerRepositoryCustomTest.java
  src/test/java/com/kdt/module/customer/domain/repository/PersistCustomerTest.java
  src/test/java/com/kdt/module/order/PersistOrderTest.java
Labels: Team-Kyu, 🔥 매운맛

#312 [4기 박상민] Springboot-jpa weekly 미션 1차 PR입니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/programmers/jpaweeklymission/JpaWeeklyMissionApplication.java
  src/main/java/org/programmers/jpaweeklymission/customer/Customer.java
  src/main/java/org/programmers/jpaweeklymission/customer/Infra/CustomerJpaRepository.java
  src/main/java/org/programmers/jpaweeklymission/customer/application/CustomerMapper.java
  src/main/java/org/programmers/jpaweeklymission/customer/application/CustomerService.java
  src/main/java/org/programmers/jpaweeklymission/customer/application/dto/CustomerResponse.java
  src/main/java/org/programmers/jpaweeklymission/customer/presentation/CustomerController.java
  src/main/java/org/programmers/jpaweeklymission/customer/presentation/dto/CustomerCreationRequest.java
  src/main/java/org/programmers/jpaweeklymission/customer/presentation/dto/CustomerUpdateRequest.java
  src/main/java/org/programmers/jpaweeklymission/global/BaseEntity.java
  src/main/java/org/programmers/jpaweeklymission/global/exception/ErrorResponse.java
  src/main/java/org/programmers/jpaweeklymission/global/exception/GlobalExceptionHandler.java
  src/main/resources/logback.xml
  src/test/java/org/programmers/jpaweeklymission/customer/CustomerTest.java
  src/test/java/org/programmers/jpaweeklymission/customer/Infra/CustomerJpaRepositoryTest.java
Labels: 🔥 매운맛, Team-Seunghoon

#330 [4기 오세한] Mission 3: Gradle 세팅
  .gitignore
  .gradle/8.2.1/checksums/checksums.lock
  .gradle/8.2.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.2.1/dependencies-accessors/gc.properties
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileChanges/last-build.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/.name
  HELP.md
  build.gradle
  build/reports/tests/test/classes/prgms.jpamission2.persistenceTest.PersistenceContextTest.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/prgms.jpamission2.persistenceTest.html
  build/resources/main/application.yaml
  build/test-results/test/TEST-prgms.jpamission2.persistenceTest.PersistenceContextTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/compileTransaction/stash-dir/DataSourceConfig.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/compileTransaction/stash-dir/PersistenceContextTest.class.uniqueId0
  build/tmp/compileTestJava/previous-compilation-data.bin
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/prgms/jpamission2/JpaMission2Application.java
  src/main/java/prgms/jpamission2/config/DataSourceConfig.java
  src/main/java/prgms/jpamission2/config/domain/Customer.java
  src/main/java/prgms/jpamission2/config/domain/CustomerRepository.java
  src/main/java/prgms/jpamission2/config/domain/order/Member.java
  src/main/resources/application.yaml
  src/test/java/prgms/jpamission2/JpaMission2ApplicationTests.java
  src/test/java/prgms/jpamission2/persistenceTest/PersistenceContextTest.java
Labels: Team-Kyu, 🔥 매운맛

#331 [4기 오세한] mission3 : 깃 캐시 제거 pr
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/js/report.js
  build/resources/main/application.yaml
  build/tmp/compileTestJava/compileTransaction/stash-dir/PersistenceContextTest.class.uniqueId0
Labels: Team-Kyu, 🔥 매운맛

#332 [4기 오세한]미션3 : 깃 캐시 제거
  build/reports/tests/test/index.html
  build/reports/tests/test/packages/prgms.jpamission2.persistenceTest.html
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/compileTransaction/stash-dir/DataSourceConfig.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
Labels: Team-Kyu, 🔥 매운맛

#292 [4기 신범철] Mission 3: 연관관계 매핑
  src/main/java/com/programmers/jpa_mission/domain/order/BaseEntity.java
  src/main/java/com/programmers/jpa_mission/domain/order/Item.java
  src/main/java/com/programmers/jpa_mission/domain/order/Member.java
  src/main/java/com/programmers/jpa_mission/domain/order/Order.java
  src/main/java/com/programmers/jpa_mission/domain/order/OrderItem.java
  src/main/java/com/programmers/jpa_mission/domain/order/OrderStatus.java
  src/test/java/com/programmers/jpa_mission/domain/CustomerRepositoryTest.java
  src/test/java/com/programmers/jpa_mission/domain/OrderPersistenceTest.java
  src/test/java/com/programmers/jpa_mission/domain/PersistenceContextTest.java
Labels: Team-Kyu, 🔥 매운맛

#289 [4기 장수연] Mission 3: 연관관계 매핑
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/kdtjpa/KdtJpaApplication.java
  src/main/java/com/example/kdtjpa/config/DataSourceConfig.java
  src/main/java/com/example/kdtjpa/domain/Customer.java
  src/main/java/com/example/kdtjpa/domain/CustomerRepository.java
  src/main/java/com/example/kdtjpa/domain/order/BaseEntity.java
  src/main/java/com/example/kdtjpa/domain/order/Item.java
  src/main/java/com/example/kdtjpa/domain/order/Member.java
  src/main/java/com/example/kdtjpa/domain/order/Order.java
  src/main/java/com/example/kdtjpa/domain/order/OrderItem.java
  src/main/java/com/example/kdtjpa/domain/order/OrderStatus.java
  src/main/resources/application.yml
  src/test/java/com/example/kdtjpa/KdtJpaApplicationTests.java
  src/test/java/com/example/kdtjpa/domain/CustomerRepositoryTest.java
  src/test/java/com/example/kdtjpa/domain/PersistenceContextTest.java
  src/test/java/com/example/kdtjpa/domain/order/OrderPersistenceTest.java
Labels: Team-Kyu, 💧 순한맛

#304 [4기 김혜민] Mission 1, 2, 3 PR 제출합니다.
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/programmers/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/programmers/springbootjpa/domain/mission1/customer/Customer.java
  src/main/java/com/programmers/springbootjpa/domain/mission1/customer/CustomerRepository.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/BaseEntity.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/item/Car.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/item/Food.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/item/Furniture.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/item/Item.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/item/ItemRepository.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/member/Member.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/member/MemberRepository.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/order/Order.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/order/OrderRepository.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/order/OrderStatus.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/orderItem/OrderItem.java
  src/main/java/com/programmers/springbootjpa/domain/mission3/orderItem/OrderItemRepository.java
  src/main/java/com/programmers/springbootjpa/global/exception/InvalidRequestValueException.java
  src/main/resources/application.yml
  src/test/java/com/programmers/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/programmers/springbootjpa/domain/mission1/customer/CustomerRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission1/customer/CustomerTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission2/PersistenceContextTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/item/CarTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/item/FoodTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/item/FurnitureTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/item/ItemRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/member/MemberRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/member/MemberTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/order/OrderRepositoryTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/order/OrderTest.java
  src/test/java/com/programmers/springbootjpa/domain/mission3/orderItem/OrderItemTest.java
Labels: Team-F, 🔥 매운맛

#309 [4기 민승현] Mission 1 : JPA 소개(단일 엔티티를 이용한 CRUD를 구현)
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/springbootjpaweekly/SpringbootJpaWeeklyApplication.java
  src/main/java/com/example/springbootjpaweekly/domain/entity/Customer.java
  src/main/java/com/example/springbootjpaweekly/domain/repository/CustomerRepository.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/com/example/springbootjpaweekly/SpringbootJpaWeeklyApplicationTests.java
  src/test/java/com/example/springbootjpaweekly/domain/repository/CustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Navy

#316 [4기-민승현] Mission 3: 연관관계 매핑
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/springbootjpaweekly3/SpringbootJpaWeekly3Application.java
  src/main/java/com/example/springbootjpaweekly3/domain/contant/OrderStatus.java
  src/main/java/com/example/springbootjpaweekly3/domain/entity/Item.java
  src/main/java/com/example/springbootjpaweekly3/domain/entity/Member.java
  src/main/java/com/example/springbootjpaweekly3/domain/entity/Order.java
  src/main/java/com/example/springbootjpaweekly3/domain/entity/OrderItem.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/com/example/springbootjpaweekly3/SpringbootJpaWeekly3ApplicationTests.java
Labels: 🔥 매운맛, Team-Navy

#286 [4기 김주웅] Weekely Mission 1, 3 PR 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/example/springbootjpa/mission1/customer/domain/Customer.java
  src/main/java/com/example/springbootjpa/mission1/customer/repository/CustomerRepository.java
  src/main/java/com/example/springbootjpa/mission3/member/domain/Member.java
  src/main/java/com/example/springbootjpa/mission3/order/domain/Item.java
  src/main/java/com/example/springbootjpa/mission3/order/domain/Order.java
  src/main/java/com/example/springbootjpa/mission3/order/domain/OrderItem.java
  src/main/resources/application.yml
  src/test/java/com/example/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/example/springbootjpa/mission1/repository/CustomerRepositoryTest.java
Labels: Team-Kyu, 🔥 매운맛

#311 [4기] 주홍석 Mission 3 연관관계 매핑 실습
  src/main/java/com/jhs/springbootjpa/model/Item.java
  src/main/java/com/jhs/springbootjpa/model/Order.java
  src/main/java/com/jhs/springbootjpa/model/OrderItem.java
  src/main/java/com/jhs/springbootjpa/model/OrderStatus.java
  src/main/java/com/jhs/springbootjpa/repository/ItemRepository.java
  src/main/java/com/jhs/springbootjpa/repository/OrderRepository.java
  src/test/java/com/jhs/springbootjpa/persistence/OrderPersistenceTest.java
Labels: Team-Ray, 🔥 매운맛

#283 [4기 김범우] Mission 3: 연관관계 매핑
  build.gradle
  src/main/java/com/lecture/jpa/domain/order/Item.java
  src/main/java/com/lecture/jpa/domain/order/Member.java
  src/main/java/com/lecture/jpa/domain/order/Order.java
  src/main/java/com/lecture/jpa/domain/order/OrderItem.java
  src/main/java/com/lecture/jpa/domain/order/OrderStatus.java
  src/test/java/com/lecture/jpa/domain/order/OrderPersistenceTest.java
Labels: Team-Ray, 🔥 매운맛

#237 [4기 배준일] Mission 1, 2, 3 제출합니다.
  jpa-weekly/.gitignore
  jpa-weekly/build.gradle
  jpa-weekly/gradle/wrapper/gradle-wrapper.jar
  jpa-weekly/gradle/wrapper/gradle-wrapper.properties
  jpa-weekly/gradlew
  jpa-weekly/gradlew.bat
  jpa-weekly/settings.gradle
  jpa-weekly/src/main/java/com/example/jpaweekly/JpaWeeklyApplication.java
  jpa-weekly/src/main/java/com/example/jpaweekly/domain/Customer.java
  jpa-weekly/src/main/java/com/example/jpaweekly/domain/Item.java
  jpa-weekly/src/main/java/com/example/jpaweekly/domain/Member.java
  jpa-weekly/src/main/java/com/example/jpaweekly/domain/Order.java
  jpa-weekly/src/main/java/com/example/jpaweekly/domain/OrderItem.java
  jpa-weekly/src/main/java/com/example/jpaweekly/domain/OrderStatus.java
  jpa-weekly/src/main/java/com/example/jpaweekly/repository/CustomerRepository.java
  jpa-weekly/src/main/resources/application.yml
  jpa-weekly/src/test/java/com/example/jpaweekly/CustomerRepositoryTest.java
  jpa-weekly/src/test/java/com/example/jpaweekly/JpaWeeklyApplicationTests.java
  jpa-weekly/src/test/java/com/example/jpaweekly/PersistenceContextTest.java
Labels: 🔥 매운맛, Team-Navy

#335 [4기 최성원] 엔티티간의 연관관계 양방향 맵핑
  README.md
  img.png
  src/main/java/com/kdt/mission1/domain/order/Item.java
  src/main/java/com/kdt/mission1/domain/order/Member.java
  src/main/java/com/kdt/mission1/domain/order/MemberRepository.java
  src/main/java/com/kdt/mission1/domain/order/Order.java
  src/main/java/com/kdt/mission1/domain/order/OrderItem.java
  src/test/java/com/kdt/mission1/domain/MemberOrderTest.java
Labels: Team-Ray, 🔥 매운맛
